import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { recipeService } from "@/application/recipes";
import { calculateRatio } from "@/domain";
type Props = { params: Promise<{ recipeId: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const recipe = await recipeService.detail((await params).recipeId); return { title: recipe?.currentVersion.title ?? "Recipe not found" }; }
export default async function RecipeDetailPage({ params }: Props) {
  const recipe = await recipeService.detail((await params).recipeId); if (!recipe) notFound(); const item = recipe.currentVersion; const ratio = calculateRatio(item.doseGrams, item.totalWaterGrams); const steps = [...item.steps].sort((a, b) => a.order - b.order);
  return <main className="recipe-detail"><div className="detail-topbar"><Link className="back-link" href="/discover">← Discover</Link><Link className="profile-link" href="/me">Me</Link></div><header><p className="eyebrow">{item.author} · {recipe.type}</p><h1>{item.title}</h1><p className="lead">{item.description}</p></header><section aria-label="Recipe parameters" className="parameter-panel"><dl><div><dt>Dose</dt><dd>{item.doseGrams} g</dd></div><div><dt>Water</dt><dd>{item.totalWaterGrams} g</dd></div>{ratio !== null && <div><dt>Ratio</dt><dd>1:{ratio.toFixed(1)}</dd></div>}<div><dt>Temperature</dt><dd>{item.temperatureCelsius}°C</dd></div><div><dt>Time</dt><dd>{Math.floor(item.expectedTimeSeconds / 60)}:{String(item.expectedTimeSeconds % 60).padStart(2, "0")}</dd></div><div><dt>Method</dt><dd>{item.method.replace("_", " ")}</dd></div><div><dt>Dripper</dt><dd>{item.dripper}</dd></div><div><dt>Grind</dt><dd>{item.grindDescription}</dd></div><div><dt>Difficulty</dt><dd>{item.difficulty}</dd></div><div><dt>Roast</dt><dd>{item.roastSuitability.map((value) => value.replace("_", " ")).join(", ")}</dd></div></dl></section><section className="steps-section"><p className="eyebrow">Recipe steps</p><h2>Follow the water, one stage at a time.</h2>{steps.length === 0 ? <p className="notice">This recipe has no usable steps yet. Choose another recipe from Discover.</p> : <ol className="recipe-steps">{steps.map((step) => <li key={step.id}><div className="step-number">{step.order}</div><div><div className="step-title"><h3>{step.title}</h3><strong>{step.targetWaterGrams} g</strong></div><p>{step.instruction}</p><p className="step-meta">Pour style: {step.pattern?.replace("_", " ") ?? "not specified"}{step.durationSeconds ? ` · ${step.durationSeconds} sec` : ""} · cumulative target</p></div></li>)}</ol>}</section><div className="sticky-cta"><div><span>Ready when you are</span><strong>{item.title}</strong></div><Link className="primary-button" href={`/recipes/${recipe.id}/prepare`}>Start Brew</Link></div></main>;
}
