import { describe, expect, it } from "vitest";
import { createFullDemoFixtures } from "@/dev/demo-fixtures";
import { classifyMigrationEntityState, cloudMigrationCheckpointSchema, cloudMigrationErrorCodeSchema, getPendingMigrationIds, MIGRATION_LOGICAL_ORDER, transitionMigrationCheckpoint, validateLocalCloudMigrationGraph, type CloudMigrationCheckpoint } from "./cloud-migration";

const now = "2026-08-04T08:00:00.000Z";
const base: CloudMigrationCheckpoint = { version: 1, userId: "user-1", status: "not_started", startedAt: null, completedAt: null, lastAttemptAt: null, profileMigrated: false, brewIdsMigrated: [], suggestedPlanIdsMigrated: [], graphVerified: false, errorCode: null };
function validGraph() { const fixtures = createFullDemoFixtures(); const plan = fixtures.plans.find((item) => item.id === "demo-plan-completed")!; const source = fixtures.brews.find((item) => item.id === plan.sourceBrewId)!; const result = fixtures.brews.find((item) => item.id === plan.resultingBrewId)!; return { profile: fixtures.profile, brews: [result, source], suggestedPlans: [plan] }; }

describe("cloud migration checkpoint", () => {
  it("accepts a versioned not_started checkpoint", () => expect(cloudMigrationCheckpointSchema.parse(base)).toEqual(base));
  it("transitions through review_required and in_progress with deterministic timestamps", () => { const review = transitionMigrationCheckpoint(base, "review_required", now); const progress = transitionMigrationCheckpoint(review, "in_progress", now); expect(review.lastAttemptAt).toBe(now); expect(progress.startedAt).toBe(now); });
  it("requires graph verification and a timestamp before completed", () => { expect(() => transitionMigrationCheckpoint(base, "completed", now)).toThrow(); const completed = transitionMigrationCheckpoint({ ...base, status: "in_progress", startedAt: now, graphVerified: true }, "completed", now); expect(completed).toMatchObject({ status: "completed", completedAt: now, errorCode: null }); });
  it("preserves partial progress when failed", () => { const failed = transitionMigrationCheckpoint({ ...base, brewIdsMigrated: ["brew-1"] }, "failed", now, "remote_write_failed"); expect(failed.brewIdsMigrated).toEqual(["brew-1"]); expect(failed.errorCode).toBe("remote_write_failed"); });
  it.each([{ ...base, userId: "" }, { ...base, startedAt: "bad" }, { ...base, brewIdsMigrated: ["a", "a"] }, { ...base, status: "completed", completedAt: now, graphVerified: false }, { ...base, status: "failed", errorCode: null }, { ...base, errorCode: "local_data_invalid" }])("rejects an invalid checkpoint", (candidate) => expect(cloudMigrationCheckpointSchema.safeParse(candidate).success).toBe(false));
  it("does not restart a completed migration", () => { const completed = { ...base, status: "completed" as const, startedAt: now, completedAt: now, lastAttemptAt: now, graphVerified: true }; expect(() => transitionMigrationCheckpoint(completed, "in_progress", now)).toThrow("migration_already_completed"); });
  it("identifies only unfinished IDs for a retry without generating IDs", () => expect(getPendingMigrationIds({ ...base, brewIdsMigrated: ["demo-brew-a"] }, ["demo-brew-b", "demo-brew-a"], ["demo-plan-a"])).toEqual({ brewIds: ["demo-brew-b"], suggestedPlanIds: ["demo-plan-a"] }));
});

describe("migration graph validation", () => {
  it("accepts an empty graph and a valid linked graph", () => { expect(validateLocalCloudMigrationGraph({ profile: null, brews: [], suggestedPlans: [] }).valid).toBe(true); expect(validateLocalCloudMigrationGraph(validGraph()).valid).toBe(true); });
  it("returns deterministic ordering, preserves demo IDs, and does not mutate input", () => { const graph = validGraph(), before = structuredClone(graph); const result = validateLocalCloudMigrationGraph(graph); expect(result.orderedBrewIds).toEqual([...result.orderedBrewIds].sort()); expect(result.orderedPlanIds).toEqual(["demo-plan-completed"]); expect(graph).toEqual(before); });
  it("detects duplicate Brew and Plan IDs", () => { const graph = validGraph(); const result = validateLocalCloudMigrationGraph({ ...graph, brews: [...graph.brews, graph.brews[0]], suggestedPlans: [...graph.suggestedPlans, graph.suggestedPlans[0]] }); expect(result.errors.map((item) => item.code)).toEqual(expect.arrayContaining(["duplicate_brew_id", "duplicate_plan_id"])); });
  it("detects missing source Brew", () => { const graph = validGraph(); expect(validateLocalCloudMigrationGraph({ ...graph, brews: graph.brews.filter((brew) => brew.id !== graph.suggestedPlans[0].sourceBrewId) }).errors.map((item) => item.code)).toContain("missing_source_brew"); });
  it("detects missing resulting Brew", () => { const graph = validGraph(); expect(validateLocalCloudMigrationGraph({ ...graph, brews: graph.brews.filter((brew) => brew.id !== graph.suggestedPlans[0].resultingBrewId) }).errors.map((item) => item.code)).toContain("missing_resulting_brew"); });
  it("detects a missing source Plan and ambiguous legacy mapping", () => { const graph = validGraph(), resultBrew = graph.brews.find((brew) => brew.sourceSuggestedPlanId)!; const errors = validateLocalCloudMigrationGraph({ ...graph, brews: [{ ...resultBrew, sourceSuggestedPlanId: "legacy-plan" }, graph.brews.find((brew) => !brew.sourceSuggestedPlanId)!] }).errors.map((item) => item.code); expect(errors).toContain("missing_source_plan"); expect(errors).toContain("mapping_mismatch"); });
  it("detects bidirectional mismatch and source metadata mismatch", () => { const graph = validGraph(), plan = { ...graph.suggestedPlans[0], sourceFingerprint: "different" }; const codes = validateLocalCloudMigrationGraph({ ...graph, suggestedPlans: [plan] }).errors.map((item) => item.code); expect(codes).toContain("result_metadata_mismatch"); });
  it("detects duplicate resulting Brew mapping", () => { const graph = validGraph(), copy = { ...graph.suggestedPlans[0], id: "demo-plan-copy" }; const codes = validateLocalCloudMigrationGraph({ ...graph, suggestedPlans: [...graph.suggestedPlans, copy] }).errors.map((item) => item.code); expect(codes).toContain("duplicate_resulting_brew"); });
  it("validates the v2 used invariant", () => { const graph = validGraph(), bad = { ...graph.suggestedPlans[0], usedAt: null }; expect(validateLocalCloudMigrationGraph({ ...graph, suggestedPlans: [bad] }).errors.map((item) => item.code)).toContain("invalid_plan_state"); });
  it("detects a missing source Analysis", () => { const graph = validGraph(), plan = { ...graph.suggestedPlans[0], sourceAnalysisId: "missing-analysis" }; expect(validateLocalCloudMigrationGraph({ ...graph, suggestedPlans: [plan] }).errors.map((item) => item.code)).toContain("missing_source_analysis"); });
  it("detects a Brew and Plan graph cycle", () => { const graph = validGraph(), plan = { ...graph.suggestedPlans[0], sourceBrewId: graph.suggestedPlans[0].resultingBrewId! }; expect(validateLocalCloudMigrationGraph({ ...graph, suggestedPlans: [plan] }).errors.map((item) => item.code)).toContain("cycle_detected"); });
  it("publishes the logical dependency order without executing it", () => expect(MIGRATION_LOGICAL_ORDER).toEqual(["profile", "brews_without_plan_links", "suggested_plans", "patch_brew_plan_links", "patch_plan_result_links", "verify_graph", "complete_checkpoint"]));
});

describe("migration idempotency classification", () => {
  const local = { id: "demo-id", title: "same" };
  it.each([[null, "missing_remote"], [{ id: "demo-id", title: "same", revision: 1 }, "matching"], [{ id: "demo-id", title: "different", revision: 1 }, "conflict"], [{ id: "demo-id", title: "same", revision: 2, deletedAt: now }, "deleted_remote"], [{ id: "", title: "same", revision: 1 }, "invalid_remote"], [{ id: "demo-id", title: "same" }, "invalid_remote"]] as const)("classifies %j as %s", (remote, expected) => expect(classifyMigrationEntityState(local, remote)).toBe(expected));
  it("treats revision-only differences as matching and preserves local ID", () => { const remote = { ...local, revision: 8 }; expect(classifyMigrationEntityState(local, remote)).toBe("matching"); expect(local.id).toBe("demo-id"); });
});

describe("safe migration error contract", () => {
  it.each(["migration_unavailable", "unauthenticated", "local_data_invalid", "remote_write_failed", "remote_verification_failed", "duplicate_remote_entity", "graph_reference_missing", "graph_reference_conflict", "revision_conflict", "checkpoint_invalid", "migration_already_completed", "unknown_migration_error"] as const)("accepts the normalized code %s", (code) => expect(cloudMigrationErrorCodeSchema.parse(code)).toBe(code));
});
