import { z } from "zod";
import type { Brew } from "./types";
import type { SuggestedBrewPlan } from "./suggested-plan";
import type { StoredUserProfile } from "@/repositories/user-profile-repository";

export const MIGRATION_BATCH_SIZE = 25;
export const migrationEngineErrorCodeSchema = z.enum(["unauthenticated","consent_required","review_outdated","migration_already_completed","local_data_invalid","checkpoint_invalid","checkpoint_write_failed","profile_conflict","remote_entity_conflict","remote_entity_deleted","remote_row_invalid","remote_write_failed","revision_conflict","duplicate_remote_entity","graph_reference_missing","graph_reference_conflict","remote_verification_failed","network_error","rate_limited","migration_interrupted","unknown_migration_error"]);
export type MigrationEngineErrorCode = z.infer<typeof migrationEngineErrorCodeSchema>;
export const migrationEntityStatusSchema = z.enum(["pending","migrated","already_present","failed","conflict"]);
export type MigrationEntityStatus = z.infer<typeof migrationEntityStatusSchema>;
export const migrationEngineCheckpointSchema = z.object({
  version:z.literal(1),userId:z.string().min(1),reviewFingerprint:z.string().min(1),status:z.enum(["review_required","in_progress","failed","completed"]),startedAt:z.string().datetime(),completedAt:z.string().datetime().nullable(),lastAttemptAt:z.string().datetime(),profileStatus:migrationEntityStatusSchema,
  migratedBrewIds:z.array(z.string().min(1)).refine((v)=>new Set(v).size===v.length),migratedSuggestedPlanIds:z.array(z.string().min(1)).refine((v)=>new Set(v).size===v.length),patchedBrewIds:z.array(z.string().min(1)).refine((v)=>new Set(v).size===v.length),patchedSuggestedPlanIds:z.array(z.string().min(1)).refine((v)=>new Set(v).size===v.length),graphVerified:z.boolean(),errorCode:migrationEngineErrorCodeSchema.nullable(),failedEntityType:z.enum(["profile","brew","suggested_plan","brew_patch","plan_patch","verification","checkpoint"]).nullable(),failedEntityId:z.string().nullable(),attemptCount:z.number().int().positive(),
  totalBrewCount:z.number().int().nonnegative(),totalSuggestedPlanCount:z.number().int().nonnegative(),totalBrewPatchCount:z.number().int().nonnegative(),totalSuggestedPlanPatchCount:z.number().int().nonnegative(),
}).superRefine((v,c)=>{if(v.status==="completed"&&(!v.graphVerified||!v.completedAt||v.errorCode||!["migrated","already_present"].includes(v.profileStatus)))c.addIssue({code:"custom",path:["status"],message:"Completed checkpoint is incomplete."});if(v.status==="failed"&&!v.errorCode)c.addIssue({code:"custom",path:["errorCode"],message:"Failed checkpoint requires errorCode."});if(v.status!=="failed"&&v.errorCode)c.addIssue({code:"custom",path:["errorCode"],message:"Only failed checkpoint may store an error."})});
export type MigrationEngineCheckpoint=z.infer<typeof migrationEngineCheckpointSchema>;
export type StartCloudMigrationCommand={consentConfirmed:true;reviewFingerprint:string};
export type MigrationEngineResult={ok:true;checkpoint:MigrationEngineCheckpoint}|{ok:false;code:MigrationEngineErrorCode;message:string;checkpoint?:MigrationEngineCheckpoint};

function stable(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`}
export function createReviewFingerprint(input:{profile:unknown;brews:readonly Brew[];suggestedPlans:readonly SuggestedBrewPlan[];recipeCount:number}){const canonical=stable({profile:input.profile,brews:[...input.brews].sort((a,b)=>a.id.localeCompare(b.id)),suggestedPlans:[...input.suggestedPlans].sort((a,b)=>a.id.localeCompare(b.id)),recipeCount:input.recipeCount});let hash=2166136261;for(let i=0;i<canonical.length;i++){hash^=canonical.charCodeAt(i);hash=Math.imul(hash,16777619)}return`review-v1-${(hash>>>0).toString(16).padStart(8,"0")}`}
export function toMigrationBaseBrew(local:Brew):Brew{return local.sourceSuggestedPlanId?{...structuredClone(local),sourceType:"recipe",sourceSuggestedPlanId:undefined}:structuredClone(local)}
export function buildBrewReferencePatch(local:Brew,remote:Brew):Brew{return{...structuredClone(remote),sourceType:local.sourceType,sourceSuggestedPlanId:local.sourceSuggestedPlanId,sourceBrewId:local.sourceBrewId,sourceAnalysisId:local.sourceAnalysisId,sourceRecommendationId:local.sourceRecommendationId,sourceFingerprint:local.sourceFingerprint,suggestedPlanHandoff:local.suggestedPlanHandoff?structuredClone(local.suggestedPlanHandoff):null}}
const profileContent=(stored:StoredUserProfile)=>({displayName:stored.profile.displayName,experienceLevel:stored.profile.experienceLevel,currentNeeds:[...stored.profile.currentNeeds].sort(),onboardingCompleted:stored.onboardingCompleted});
export type ProfileMigrationState="missing_remote"|"bootstrap"|"matching"|"profile_conflict";
export function classifyProfileMigrationState(local:StoredUserProfile,remote:StoredUserProfile|null):ProfileMigrationState{if(!remote)return"missing_remote";if(stable(profileContent(local))===stable(profileContent(remote)))return"matching";const bootstrap=!remote.onboardingCompleted&&remote.profile.experienceLevel==="beginner"&&remote.selectedNeeds.length===0&&remote.profile.currentNeeds.length===0&&remote.profile.displayName==="Coffee Brewer";return bootstrap?"bootstrap":"profile_conflict"}
const withoutDatabaseMetadata=(value:unknown)=>value&&typeof value==="object"&&!Array.isArray(value)?Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([key])=>key!=="updatedAt"&&key!=="revision"&&key!=="deletedAt")):value;
export function sameMigrationEntity<T>(local:T,remote:T){return stable(withoutDatabaseMetadata(local))===stable(withoutDatabaseMetadata(remote))}
export function chunkMigrationIds(ids:readonly string[],size=MIGRATION_BATCH_SIZE){const sorted=[...ids].sort(),chunks:string[][]=[];for(let i=0;i<sorted.length;i+=size)chunks.push(sorted.slice(i,i+size));return chunks}
