import { readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { AuthApiError, createClient, type User } from "@supabase/supabase-js";
import { describe, expect, it, vi } from "vitest";
import type { Database } from "@/types/database.types";
import { LocalBrewRepository } from "@/repositories/local-brew-repository";
import { LocalSuggestedPlanRepository } from "@/repositories/local-suggested-plan-repository";
import { LocalUserProfileRepository } from "@/repositories/local-user-profile-repository";
import { MockRecipeRepository } from "@/repositories/mock-recipe-repository";
import { createAuthenticatedRemoteRepositoryBundle, createLocalRepositoryBundle, createMigrationRepositoryBundle, getRepositoryDiagnostics, getRuntimeRepositoryBundle, RUNTIME_REPOSITORY_MODE, RUNTIME_REPOSITORY_POLICY } from "./repository-composition";

const user: User = { id: "11111111-1111-4111-8111-111111111111", aud: "authenticated", role: "authenticated", email: "hidden@example.test", app_metadata: {}, user_metadata: {}, created_at: "2026-08-01T00:00:00.000Z" };
function clientWithUser(authenticated = true) {
  const fetch = vi.fn(async () => new Response("[]", { status: 200, headers: { "Content-Type": "application/json" } }));
  const client = createClient<Database>("https://example.supabase.co", "sb_publishable_test", { global: { fetch }, auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } });
  const getUser = vi.spyOn(client.auth, "getUser").mockResolvedValue(authenticated ? { data: { user }, error: null } : { data: { user: null }, error: new AuthApiError("No session", 401, "session_not_found") });
  return { client, fetch, getUser };
}

describe("repository composition", () => {
  it("creates the complete Local bundle without touching browser storage", () => { const getItem = vi.fn(); const original = Object.getOwnPropertyDescriptor(globalThis, "localStorage"); Object.defineProperty(globalThis, "localStorage", { configurable: true, value: { getItem, setItem: vi.fn() } }); try { const bundle = createLocalRepositoryBundle(); expect(bundle.userProfileRepository).toBeInstanceOf(LocalUserProfileRepository); expect(bundle.brewRepository).toBeInstanceOf(LocalBrewRepository); expect(bundle.suggestedPlanRepository).toBeInstanceOf(LocalSuggestedPlanRepository); expect(bundle.recipeRepository).toBeInstanceOf(MockRecipeRepository); expect(getItem).not.toHaveBeenCalled(); } finally { if (original) Object.defineProperty(globalThis, "localStorage", original); else Reflect.deleteProperty(globalThis, "localStorage"); } });
  it("keeps runtime mode and policy explicitly local", () => { expect(RUNTIME_REPOSITORY_MODE).toBe("local"); expect(RUNTIME_REPOSITORY_POLICY).toEqual({ mode: "local", reason: "cloud_migration_not_completed" }); expect(getRuntimeRepositoryBundle().brewRepository).toBeInstanceOf(LocalBrewRepository); });
  it.each([["authenticated", true], ["local", true], ["authenticated", false]] as const)("does not use auth or remote availability to switch runtime (%s/%s)", (authMode, available) => { expect(getRepositoryDiagnostics(authMode, available).runtimeRepositoryMode).toBe("local"); expect(getRuntimeRepositoryBundle().suggestedPlanRepository).toBeInstanceOf(LocalSuggestedPlanRepository); });
  it("does not use environment, development mode, or URL query as selection inputs", () => { expect(getRuntimeRepositoryBundle.length).toBe(0); const source = readFileSync(resolve(process.cwd(), "src/infrastructure/repositories/repository-composition.ts"), "utf8"); expect(source).not.toMatch(/NODE_ENV|location\.search|URLSearchParams|NEXT_PUBLIC_SUPABASE/); });
  it("does not initialize Supabase when the runtime bundle is created", () => { const source = readFileSync(resolve(process.cwd(), "src/lib/supabase/client.ts"), "utf8"); expect(source).toContain("if (browserClient) return browserClient"); expect(() => getRuntimeRepositoryBundle()).not.toThrow(); });
  it("returns unauthenticated instead of constructing remote repositories", async () => { const fake = clientWithUser(false); const result = await createAuthenticatedRemoteRepositoryBundle(() => fake.client); expect(result).toEqual(expect.objectContaining({ ok: false, code: "unauthenticated" })); expect(fake.fetch).not.toHaveBeenCalled(); });
  it("constructs authenticated remote repositories without caller userId or data query", async () => { const fake = clientWithUser(); const result = await createAuthenticatedRemoteRepositoryBundle(() => fake.client); expect(result.ok && result.authenticatedUserId).toBe(user.id); expect(result.ok && Object.keys(result.value).sort()).toEqual(["brewRepository", "suggestedPlanRepository", "userProfileRepository"]); expect(fake.getUser).toHaveBeenCalledOnce(); expect(fake.fetch).not.toHaveBeenCalled(); expect(createAuthenticatedRemoteRepositoryBundle.length).toBeLessThanOrEqual(1); });
  it("maps missing Supabase configuration to migration_unavailable while Local stays usable", async () => { const result = await createAuthenticatedRemoteRepositoryBundle(() => { throw new Error("missing env"); }); expect(result).toEqual(expect.objectContaining({ ok: false, code: "migration_unavailable" })); expect(getRuntimeRepositoryBundle().userProfileRepository).toBeInstanceOf(LocalUserProfileRepository); });
  it("creates a dependency-only migration bundle without local or remote data access", async () => { const fake = clientWithUser(); const getItem = vi.fn(), setItem = vi.fn(); const original = Object.getOwnPropertyDescriptor(globalThis, "localStorage"); Object.defineProperty(globalThis, "localStorage", { configurable: true, value: { getItem, setItem } }); try { const result = await createMigrationRepositoryBundle(() => fake.client); expect(result.ok && result.value.authenticatedUserId).toBe(user.id); expect(result.ok && result.value.local.brewRepository).toBeInstanceOf(LocalBrewRepository); expect(result.ok && Object.keys(result.value.remote)).toHaveLength(3); expect(getItem).not.toHaveBeenCalled(); expect(setItem).not.toHaveBeenCalled(); expect(fake.fetch).not.toHaveBeenCalled(); } finally { if (original) Object.defineProperty(globalThis, "localStorage", original); else Reflect.deleteProperty(globalThis, "localStorage"); } });
  it("refuses a migration bundle without authentication", async () => { const fake = clientWithUser(false); expect(await createMigrationRepositoryBundle(() => fake.client)).toEqual(expect.objectContaining({ ok: false, code: "unauthenticated" })); });
  it("reports Local auth diagnostics without migration readiness", () => expect(getRepositoryDiagnostics("local", false)).toEqual({ authMode: "local", runtimeRepositoryMode: "local", remoteRepositoryAvailability: "unavailable", migrationReadiness: "unavailable", migrationStatus: "not_started" }));
  it("reports authenticated dependency readiness without changing runtime", () => expect(getRepositoryDiagnostics("authenticated", true)).toEqual(expect.objectContaining({ runtimeRepositoryMode: "local", migrationReadiness: "dependencies_ready", migrationStatus: "not_started" })));
  it("keeps Recipe reads in the Local runtime bundle", async () => expect((await getRuntimeRepositoryBundle().recipeRepository.listRecipes()).length).toBeGreaterThanOrEqual(5));
  it("creates fresh dependency bundles without singleton state mutation", () => { const first = createLocalRepositoryBundle(), second = createLocalRepositoryBundle(); expect(first).not.toBe(second); expect(first.brewRepository).not.toBe(second.brewRepository); });
  it("does not expose repository switching operations", () => { const source = readFileSync(resolve(process.cwd(), "src/infrastructure/repositories/repository-composition.ts"), "utf8"); expect(source).not.toMatch(/setRepositoryMode|switchToRemote|featureFlag/); });
  it("keeps ordinary product routes free of Supabase repositories and migration writes", () => { const migrationOnly=["migration-review.tsx","migration-qa-panel.tsx","local-to-cloud-migration-service.ts","migration-remote-preflight-service.ts"];const production = ["src/app", "src/components", "src/application", "src/dev"].flatMap((directory) => readdirSync(resolve(process.cwd(), directory), { recursive: true, withFileTypes: true }).filter((entry) => entry.isFile() && /\.[cm]?[jt]sx?$/.test(entry.name) && !entry.name.includes(".test.")).map((entry) => resolve(entry.parentPath, entry.name))).filter((file)=>!migrationOnly.some((name)=>file.endsWith(name))); for (const file of production) { const source = readFileSync(file, "utf8"); expect(source).not.toMatch(/Supabase(?:UserProfile|Brew|SuggestedPlan)Repository|createMigrationRepositoryBundle/); } });
});
