import { z } from "zod";
import { migrationEngineCheckpointSchema, type MigrationEngineCheckpoint } from "@/domain";
export const CLOUD_MIGRATION_CHECKPOINT_KEY="cupmaster:cloud-migration";
const envelopeSchema=z.object({version:z.literal(1),data:z.object({checkpoints:z.array(migrationEngineCheckpointSchema).refine((v)=>new Set(v.map(x=>x.userId)).size===v.length)})});
type StorageLike=Pick<Storage,"getItem"|"setItem">;
export type CheckpointRead={ok:true;value:MigrationEngineCheckpoint|null}|{ok:false;code:"checkpoint_invalid";message:string};
export class CloudMigrationCheckpointRepository{
 constructor(private readonly storage?:StorageLike){}
 private getStorage(){if(this.storage)return this.storage;try{return typeof window==="undefined"?undefined:window.localStorage}catch{return undefined}}
 private readAll(){const storage=this.getStorage();if(!storage)return{ok:false as const,code:"checkpoint_invalid" as const,message:"Migration checkpoint storage is unavailable.",value:[] as MigrationEngineCheckpoint[]};try{const raw=storage.getItem(CLOUD_MIGRATION_CHECKPOINT_KEY);if(!raw)return{ok:true as const,value:[] as MigrationEngineCheckpoint[]};const parsed=envelopeSchema.safeParse(JSON.parse(raw));return parsed.success?{ok:true as const,value:parsed.data.data.checkpoints}:{ok:false as const,code:"checkpoint_invalid" as const,message:"Saved migration progress is incompatible or damaged.",value:[] as MigrationEngineCheckpoint[]}}catch{return{ok:false as const,code:"checkpoint_invalid" as const,message:"Saved migration progress could not be read.",value:[] as MigrationEngineCheckpoint[]}}
 }
 getForCurrentUser(userId:string):CheckpointRead{const result=this.readAll();return result.ok?{ok:true,value:result.value.find(x=>x.userId===userId)??null}:{ok:false,code:result.code,message:result.message}}
 private persist(checkpoints:MigrationEngineCheckpoint[]){const storage=this.getStorage(),parsed=envelopeSchema.safeParse({version:1,data:{checkpoints}});if(!storage||!parsed.success)return{ok:false as const,code:"checkpoint_write_failed" as const,message:"Migration progress could not be saved."};try{storage.setItem(CLOUD_MIGRATION_CHECKPOINT_KEY,JSON.stringify(parsed.data));return{ok:true as const}}catch{return{ok:false as const,code:"checkpoint_write_failed" as const,message:"Migration progress could not be saved."}}}
 create(checkpoint:MigrationEngineCheckpoint){const all=this.readAll();if(!all.ok)return{ok:false as const,code:all.code,message:all.message};if(all.value.some(x=>x.userId===checkpoint.userId))return{ok:false as const,code:"checkpoint_invalid" as const,message:"A checkpoint already exists for this account."};const saved=this.persist([...all.value,checkpoint]);return saved.ok?{ok:true as const,value:checkpoint}:saved}
 update(checkpoint:MigrationEngineCheckpoint){const all=this.readAll();if(!all.ok)return{ok:false as const,code:all.code,message:all.message};const index=all.value.findIndex(x=>x.userId===checkpoint.userId);if(index<0)return{ok:false as const,code:"checkpoint_invalid" as const,message:"Migration checkpoint was not found."};const next=[...all.value];next[index]=migrationEngineCheckpointSchema.parse(checkpoint);const saved=this.persist(next);return saved.ok?{ok:true as const,value:checkpoint}:saved}
 markCompleted(checkpoint:MigrationEngineCheckpoint){return this.update(migrationEngineCheckpointSchema.parse({...checkpoint,status:"completed",graphVerified:true,errorCode:null,failedEntityType:null,failedEntityId:null}))}
 clearFailedAttempt(userId:string){const read=this.getForCurrentUser(userId);if(!read.ok||!read.value)return read;return this.update({...read.value,errorCode:null,failedEntityType:null,failedEntityId:null,status:"in_progress"})}
 removeForCurrentUser(userId:string){const all=this.readAll();if(!all.ok)return{ok:false as const,code:all.code,message:all.message};const next=all.value.filter((checkpoint)=>checkpoint.userId!==userId);const saved=this.persist(next);return saved.ok?{ok:true as const,removed:next.length!==all.value.length}:saved}
}
