import{describe,expect,it,vi}from"vitest";import{migrationEngineCheckpointSchema,type MigrationEngineCheckpoint}from"@/domain";import{CLOUD_MIGRATION_CHECKPOINT_KEY,CloudMigrationCheckpointRepository}from"./cloud-migration-checkpoint-repository";
const now="2026-08-05T00:00:00.000Z";const checkpoint=(userId="user-a"):MigrationEngineCheckpoint=>migrationEngineCheckpointSchema.parse({version:1,userId,reviewFingerprint:"review-v1-test",status:"in_progress",startedAt:now,completedAt:null,lastAttemptAt:now,profileStatus:"pending",migratedBrewIds:[],migratedSuggestedPlanIds:[],patchedBrewIds:[],patchedSuggestedPlanIds:[],graphVerified:false,errorCode:null,failedEntityType:null,failedEntityId:null,attemptCount:1,totalBrewCount:2,totalSuggestedPlanCount:1,totalBrewPatchCount:1,totalSuggestedPlanPatchCount:0});
function memory(initial:string|null=null){let raw=initial;return{storage:{getItem:vi.fn(()=>raw),setItem:vi.fn((_k:string,v:string)=>{raw=v})},raw:()=>raw}}
describe("CloudMigrationCheckpointRepository",()=>{
 it("creates a versioned checkpoint envelope",()=>{const m=memory(),r=new CloudMigrationCheckpointRepository(m.storage);expect(r.create(checkpoint()).ok).toBe(true);expect(JSON.parse(m.raw()!)).toMatchObject({version:1,data:{checkpoints:[{userId:"user-a",reviewFingerprint:"review-v1-test"}]}})});
 it("isolates checkpoints by authenticated user id",()=>{const m=memory(),r=new CloudMigrationCheckpointRepository(m.storage);r.create(checkpoint("user-a"));r.create(checkpoint("user-b"));const a=r.getForCurrentUser("user-a"),b=r.getForCurrentUser("user-b");expect(a.ok&&a.value?.userId).toBe("user-a");expect(b.ok&&b.value?.userId).toBe("user-b")});
 it("returns a safe fallback for corrupted JSON",()=>expect(new CloudMigrationCheckpointRepository(memory("{").storage).getForCurrentUser("user-a")).toMatchObject({ok:false,code:"checkpoint_invalid"}));
 it("returns a safe fallback for the wrong version",()=>expect(new CloudMigrationCheckpointRepository(memory(JSON.stringify({version:2,data:{checkpoints:[]}})).storage).getForCurrentUser("user-a")).toMatchObject({ok:false,code:"checkpoint_invalid"}));
 it("does not persist entity payloads or credentials",()=>{const m=memory(),r=new CloudMigrationCheckpointRepository(m.storage);r.create(checkpoint());expect(m.raw()).not.toMatch(/recipeSnapshot|stageResults|password|access_token|refresh_token|email/)});
 it("preserves partial progress on failed checkpoints",()=>{const m=memory(),r=new CloudMigrationCheckpointRepository(m.storage),cp={...checkpoint(),status:"failed" as const,errorCode:"remote_write_failed" as const,failedEntityType:"brew" as const,failedEntityId:"brew-1",migratedBrewIds:["brew-0"]};r.create(cp);const read=r.getForCurrentUser("user-a");expect(read.ok&&read.value).toMatchObject({migratedBrewIds:["brew-0"],failedEntityId:"brew-1"})});
 it("represents in-progress work for interrupted recovery",()=>{const m=memory(),r=new CloudMigrationCheckpointRepository(m.storage);r.create(checkpoint());const read=r.getForCurrentUser("user-a");expect(read.ok&&read.value?.status).toBe("in_progress")});
 it("rejects completed checkpoints without graph verification",()=>expect(migrationEngineCheckpointSchema.safeParse({...checkpoint(),status:"completed",completedAt:now}).success).toBe(false));
 it("marks only a verified checkpoint completed",()=>{const m=memory(),r=new CloudMigrationCheckpointRepository(m.storage),cp={...checkpoint(),profileStatus:"migrated" as const,graphVerified:true,completedAt:now};r.create(cp);const result=r.markCompleted(cp);expect(result.ok&&result.value?.status).toBe("completed")});
 it("reports write failures without pretending success",()=>{const storage={getItem:()=>null,setItem:()=>{throw new Error("blocked")}};expect(new CloudMigrationCheckpointRepository(storage).create(checkpoint())).toMatchObject({ok:false,code:"checkpoint_write_failed"})});
 it("uses only its dedicated key and never localStorage.clear",()=>{const m=memory(),r=new CloudMigrationCheckpointRepository(m.storage);r.create(checkpoint());expect(m.storage.setItem).toHaveBeenCalledWith(CLOUD_MIGRATION_CHECKPOINT_KEY,expect.any(String));expect("clear" in m.storage).toBe(false)});
 it("removes only the current account checkpoint",()=>{const m=memory(),r=new CloudMigrationCheckpointRepository(m.storage),other=checkpoint("user-b");r.create(checkpoint());r.create(other);expect(r.removeForCurrentUser("user-a")).toEqual({ok:true,removed:true});expect(r.getForCurrentUser("user-a")).toEqual({ok:true,value:null});expect(r.getForCurrentUser("user-b")).toEqual({ok:true,value:other})});
});
