import type { Brew } from "@/domain";
import { brewPersistenceSchema as brewSchema, brewPersistenceSchema, localBrewPersistenceEnvelopeSchema, localBrewEnvelopeShapeSchema, LOCAL_BREW_VERSION } from "@/data/local-brew-schema";
import type { BrewReadResult, BrewRepository, BrewWriteResult } from "./brew-repository";
export const LOCAL_BREW_KEY = "cupmaster:brews";
type StorageLike = Pick<Storage, "getItem" | "setItem">;
type Hydrated = { brews: Brew[]; notice?: string };
export class LocalBrewRepository implements BrewRepository {
  constructor(private readonly storage?: StorageLike) {}
  private getStorage() { if (this.storage) return this.storage; try { return typeof window === "undefined" ? undefined : window.localStorage; } catch { return undefined; } }
  private hydrate(): BrewReadResult<Hydrated> {
    const storage = this.getStorage(); if (!storage) return { ok: false, value: { brews: [] }, message: "Local Brew storage is unavailable." };
    let raw: string | null; try { raw = storage.getItem(LOCAL_BREW_KEY); } catch { return { ok: false, value: { brews: [] }, message: "Brew drafts could not be read." }; }
    if (!raw) return { ok: true, value: { brews: [] } };
    try {
      const envelope = localBrewEnvelopeShapeSchema.safeParse(JSON.parse(raw)); if (!envelope.success) return { ok: false, value: { brews: [] }, message: "Saved Brew data uses an incompatible format." };
      const valid: Brew[] = []; let rejected = 0; const ids = new Set<string>();
      for (const candidate of envelope.data.data.brews) { const parsed = brewPersistenceSchema.safeParse(candidate); if (!parsed.success || ids.has(parsed.data.id)) { rejected += 1; continue; } ids.add(parsed.data.id); valid.push(parsed.data); }
      return { ok: true, value: { brews: valid, ...(rejected > 0 && { notice: `${rejected} damaged or duplicate Brew draft was ignored; valid drafts were preserved.` }) } };
    } catch { return { ok: false, value: { brews: [] }, message: "Saved Brew data was damaged. A safe empty list is being used." }; }
  }
  private persist(brews: Brew[]): { ok: true } | { ok: false; message: string } { const storage = this.getStorage(); if (!storage) return { ok: false, message: "Local Brew storage is unavailable." }; const envelope = localBrewPersistenceEnvelopeSchema.safeParse({ version: LOCAL_BREW_VERSION, data: { brews } }); if (!envelope.success) return { ok: false, message: "The Brew draft could not be validated before saving." }; try { storage.setItem(LOCAL_BREW_KEY, JSON.stringify(envelope.data)); return { ok: true }; } catch { return { ok: false, message: "The Brew draft could not be saved. Browser storage may be full or blocked." }; } }
  createDraft(draft: Brew): BrewWriteResult { const parsed = brewSchema.safeParse(draft); if (!parsed.success) return { ok: false, message: "The Brew draft is invalid." }; const loaded = this.hydrate(); const brews = loaded.value.brews; if (brews.some((item) => item.id === draft.id)) return { ok: false, message: "This Brew draft already exists." }; const saved = this.persist([...brews, parsed.data]); return saved.ok ? { ok: true, value: parsed.data } : saved; }
  getById(id: string): BrewReadResult<Brew | null> { const loaded = this.hydrate(); const found = loaded.value.brews.find((brew) => brew.id === id) ?? null; return loaded.ok ? { ok: true, value: found, ...(loaded.value.notice && { notice: loaded.value.notice }) } : { ok: false, value: found, message: loaded.message }; }
  findBySourceSuggestedPlanId(planId:string):BrewReadResult<Brew|null>{const loaded=this.hydrate(),matches=loaded.value.brews.filter((brew)=>brew.sourceType==="suggested_plan"&&brew.sourceSuggestedPlanId===planId);if(matches.length>1)return{ok:false,value:null,message:"duplicate_resulting_brew"};return loaded.ok?{ok:true,value:matches[0]??null}:{ok:false,value:matches[0]??null,message:loaded.message}}
  listAll(): BrewReadResult<Brew[]> { const loaded = this.hydrate(); const brews = [...loaded.value.brews]; return loaded.ok ? { ok: true, value: brews, ...(loaded.value.notice && { notice: loaded.value.notice }) } : { ok: false, value: brews, message: loaded.message }; }
  listDrafts(): BrewReadResult<Brew[]> { const loaded = this.hydrate(); const drafts = loaded.value.brews.filter((brew) => brew.recordStatus === "draft"); return loaded.ok ? { ok: true, value: drafts, ...(loaded.value.notice && { notice: loaded.value.notice }) } : { ok: false, value: drafts, message: loaded.message }; }
  listJournalEntries(): BrewReadResult<Brew[]> { const loaded = this.hydrate(); const entries = loaded.value.brews.filter((brew) => brew.executionStatus === "completed" && (brew.recordStatus === "draft" || brew.recordStatus === "saved")).sort((a, b) => (b.completedAt ?? b.updatedAt).localeCompare(a.completedAt ?? a.updatedAt) || a.id.localeCompare(b.id)); return loaded.ok ? { ok: true, value: entries, ...(loaded.value.notice && { notice: loaded.value.notice }) } : { ok: false, value: entries, message: loaded.message }; }
  upsertMany(drafts:Brew[],idPrefix:string):BrewReadResult<Brew[]>{const parsed=drafts.map((draft)=>brewPersistenceSchema.safeParse(draft));if(parsed.some((item)=>!item.success))return{ok:false,value:[],message:"Demo Brew fixtures are invalid."};const ids=new Set(drafts.map((draft)=>draft.id));if(ids.size!==drafts.length||drafts.some((draft)=>!draft.id.startsWith(idPrefix)))return{ok:false,value:[],message:"Demo Brew fixture IDs are invalid."};const loaded=this.hydrate();if(!loaded.ok)return{ok:false,value:[],message:loaded.message};const preserved=loaded.value.brews.filter((brew)=>!ids.has(brew.id));const valid=parsed.flatMap((item)=>item.success?[item.data]:[]),next=[...preserved,...valid],saved=this.persist(next);return saved.ok?{ok:true,value:next}:{ok:false,value:loaded.value.brews,message:saved.message}}
  removeByIdPrefix(idPrefix:string){const loaded=this.hydrate();if(!loaded.ok)return{ok:false as const,message:loaded.message};const next=loaded.value.brews.filter((brew)=>!brew.id.startsWith(idPrefix)),removed=loaded.value.brews.length-next.length,saved=this.persist(next);return saved.ok?{ok:true as const,removed}:{ok:false as const,message:saved.message}}
  updateDraft(draft: Brew): BrewWriteResult { const parsed = brewSchema.safeParse(draft); if (!parsed.success) return { ok: false, message: "The Brew draft update is invalid." }; const loaded = this.hydrate(); const index = loaded.value.brews.findIndex((brew) => brew.id === draft.id); if (index < 0) return { ok: false, message: "The Brew draft no longer exists." }; const next = [...loaded.value.brews]; next[index] = parsed.data; const saved = this.persist(next); return saved.ok ? { ok: true, value: parsed.data } : saved; }
  deleteDraft(id: string) { const loaded = this.hydrate(); const next = loaded.value.brews.filter((brew) => brew.id !== id); if (next.length === loaded.value.brews.length) return { ok: false as const, message: "The Brew draft no longer exists." }; return this.persist(next); }
}
