"use client";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Brew } from "@/domain";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import type { Database, Tables } from "@/types/database.types";
import { fromBrewRow, toBrewInsert, toBrewUpdate } from "./mappers/brew-mapper";
import { mapPostgrestError, mapRepositoryException, remoteFailure } from "./repository-errors";
import type { RemoteBrewRepository, RemoteMigrationRecord, RemoteResult } from "./remote-repository-contracts";

export class SupabaseBrewRepository implements RemoteBrewRepository {
  constructor(private readonly client: SupabaseClient<Database> = getSupabaseBrowserClient()) {}
  private async userId(): Promise<RemoteResult<string>> { const { data, error } = await this.client.auth.getUser(); return error || !data.user ? remoteFailure("unauthenticated", "Sign in is required for cloud persistence.") : { ok: true, value: data.user.id }; }
  private mapped(row: Tables<"brews">): RemoteResult<Brew> { try { const mapped = fromBrewRow(row); return { ok: true, value: mapped.entity, revision: mapped.revision }; } catch (error) { return mapRepositoryException(error); } }
  private async rows(query: PromiseLike<{ data: Tables<"brews">[] | null; error: import("@supabase/supabase-js").PostgrestError | null }>): Promise<RemoteResult<Brew[]>> { const { data, error } = await query; if (error) return mapPostgrestError(error); try { return { ok: true, value: (data ?? []).map((row) => fromBrewRow(row).entity) }; } catch (cause) { return mapRepositoryException(cause); } }
  async createDraft(draft: Brew): Promise<RemoteResult<Brew>> { const user = await this.userId(); if (!user.ok) return user; const { data, error } = await this.client.from("brews").insert(toBrewInsert(user.value, draft)).select("*").single(); return error ? mapPostgrestError(error) : this.mapped(data); }
  async getById(id: string): Promise<RemoteResult<Brew | null>> { const user = await this.userId(); if (!user.ok) return user; const { data, error } = await this.client.from("brews").select("*").eq("user_id", user.value).eq("id", id).is("deleted_at", null).maybeSingle(); if (error) return mapPostgrestError(error); return data ? this.mapped(data) : { ok: true, value: null }; }
  async getForMigration(id:string):Promise<RemoteResult<RemoteMigrationRecord<Brew>>>{const user=await this.userId();if(!user.ok)return user;const{data,error}=await this.client.from("brews").select("*").eq("user_id",user.value).eq("id",id).maybeSingle();if(error)return mapPostgrestError(error);if(!data)return{ok:true,value:{state:"missing"}};if(data.deleted_at)return{ok:true,value:{state:"deleted",revision:data.revision}};const mapped=this.mapped(data);return mapped.ok?{ok:true,value:{state:"active",entity:mapped.value,revision:mapped.revision??data.revision}}:{ok:true,value:{state:"invalid"}}}
  async findBySourceSuggestedPlanId(planId: string): Promise<RemoteResult<Brew | null>> { const user = await this.userId(); if (!user.ok) return user; const { data, error } = await this.client.from("brews").select("*").eq("user_id", user.value).eq("source_suggested_plan_id", planId).is("deleted_at", null).order("updated_at", { ascending: false }).limit(1).maybeSingle(); if (error) return mapPostgrestError(error); return data ? this.mapped(data) : { ok: true, value: null }; }
  async listAll(): Promise<RemoteResult<Brew[]>> { const user = await this.userId(); if (!user.ok) return user; return this.rows(this.client.from("brews").select("*").eq("user_id", user.value).is("deleted_at", null).order("updated_at", { ascending: false })); }
  async listDrafts(): Promise<RemoteResult<Brew[]>> { const user = await this.userId(); if (!user.ok) return user; return this.rows(this.client.from("brews").select("*").eq("user_id", user.value).eq("record_status", "draft").is("deleted_at", null).order("updated_at", { ascending: false })); }
  async listJournalEntries(): Promise<RemoteResult<Brew[]>> { const user = await this.userId(); if (!user.ok) return user; return this.rows(this.client.from("brews").select("*").eq("user_id", user.value).in("record_status", ["saved", "archived"]).is("deleted_at", null).order("updated_at", { ascending: false })); }
  async updateIfRevision(draft: Brew, expectedRevision: number): Promise<RemoteResult<Brew>> { const user = await this.userId(); if (!user.ok) return user; const { data, error } = await this.client.from("brews").update(toBrewUpdate(draft, expectedRevision + 1)).eq("user_id", user.value).eq("id", draft.id).eq("revision", expectedRevision).is("deleted_at", null).select("*").maybeSingle(); if (error) return mapPostgrestError(error); return data ? this.mapped(data) : remoteFailure("revision_conflict", "The cloud Brew changed before this write completed."); }
  async updateDraft(draft: Brew): Promise<RemoteResult<Brew>> { const current = await this.getById(draft.id); if (!current.ok) return current; if (!current.value || current.revision === undefined) return remoteFailure("not_found", "Cloud Brew was not found."); return this.updateIfRevision(draft, current.revision); }
  async deleteDraft(id: string): Promise<RemoteResult<null>> { const current = await this.getById(id); if (!current.ok) return current; if (!current.value || current.revision === undefined) return remoteFailure("not_found", "Cloud Brew was not found."); const user = await this.userId(); if (!user.ok) return user; const now = new Date().toISOString(); const { data, error } = await this.client.from("brews").update({ deleted_at: now, updated_at: now, revision: current.revision + 1 }).eq("user_id", user.value).eq("id", id).eq("revision", current.revision).is("deleted_at", null).select("id").maybeSingle(); if (error) return mapPostgrestError(error); return data ? { ok: true, value: null } : remoteFailure("revision_conflict", "The cloud Brew changed before deletion."); }
  async upsertMany(drafts: Brew[], idPrefix: string): Promise<RemoteResult<Brew[]>> { const saved: Brew[] = []; for (const draft of drafts) { if (!draft.id.startsWith(idPrefix)) return remoteFailure("invalid_data", "Brew ID is outside the requested prefix."); const existing = await this.getById(draft.id); if (!existing.ok) return existing; const result = existing.value ? await this.updateDraft(draft) : await this.createDraft(draft); if (!result.ok) return result; saved.push(result.value); } return { ok: true, value: saved }; }
  async removeByIdPrefix(idPrefix: string): Promise<RemoteResult<number>> { const all = await this.listAll(); if (!all.ok) return all; let removed = 0; for (const brew of all.value.filter((item) => item.id.startsWith(idPrefix))) { const result = await this.deleteDraft(brew.id); if (!result.ok) return result; removed++; } return { ok: true, value: removed }; }
}
