"use client";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { SuggestedBrewPlan } from "@/domain";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import type { Database, Tables } from "@/types/database.types";
import { fromSuggestedPlanRow, toSuggestedPlanInsert, toSuggestedPlanUpdate } from "./mappers/suggested-plan-mapper";
import { mapPostgrestError, mapRepositoryException, remoteFailure } from "./repository-errors";
import type { RemoteMigrationRecord, RemoteResult, RemoteSuggestedPlanRepository } from "./remote-repository-contracts";

export class SupabaseSuggestedPlanRepository implements RemoteSuggestedPlanRepository {
  constructor(private readonly client: SupabaseClient<Database> = getSupabaseBrowserClient()) {}
  private async userId(): Promise<RemoteResult<string>> { const { data, error } = await this.client.auth.getUser(); return error || !data.user ? remoteFailure("unauthenticated", "Sign in is required for cloud persistence.") : { ok: true, value: data.user.id }; }
  private mapped(row: Tables<"suggested_plans">): RemoteResult<SuggestedBrewPlan> { try { const mapped = fromSuggestedPlanRow(row); return { ok: true, value: mapped.entity, revision: mapped.revision }; } catch (error) { return mapRepositoryException(error); } }
  private async rows(query: PromiseLike<{ data: Tables<"suggested_plans">[] | null; error: import("@supabase/supabase-js").PostgrestError | null }>): Promise<RemoteResult<SuggestedBrewPlan[]>> { const { data, error } = await query; if (error) return mapPostgrestError(error); try { return { ok: true, value: (data ?? []).map((row) => fromSuggestedPlanRow(row).entity) }; } catch (cause) { return mapRepositoryException(cause); } }
  async create(plan: SuggestedBrewPlan): Promise<RemoteResult<SuggestedBrewPlan>> { const user = await this.userId(); if (!user.ok) return user; const { data, error } = await this.client.from("suggested_plans").insert(toSuggestedPlanInsert(user.value, plan)).select("*").single(); return error ? mapPostgrestError(error) : this.mapped(data); }
  async getById(id: string): Promise<RemoteResult<SuggestedBrewPlan | null>> { const user = await this.userId(); if (!user.ok) return user; const { data, error } = await this.client.from("suggested_plans").select("*").eq("user_id", user.value).eq("id", id).is("deleted_at", null).maybeSingle(); if (error) return mapPostgrestError(error); return data ? this.mapped(data) : { ok: true, value: null }; }
  async getForMigration(id:string):Promise<RemoteResult<RemoteMigrationRecord<SuggestedBrewPlan>>>{const user=await this.userId();if(!user.ok)return user;const{data,error}=await this.client.from("suggested_plans").select("*").eq("user_id",user.value).eq("id",id).maybeSingle();if(error)return mapPostgrestError(error);if(!data)return{ok:true,value:{state:"missing"}};if(data.deleted_at)return{ok:true,value:{state:"deleted",revision:data.revision}};const mapped=this.mapped(data);return mapped.ok?{ok:true,value:{state:"active",entity:mapped.value,revision:mapped.revision??data.revision}}:{ok:true,value:{state:"invalid"}}}
  async findByResultingBrewId(brewId: string): Promise<RemoteResult<SuggestedBrewPlan | null>> { const user = await this.userId(); if (!user.ok) return user; const { data, error } = await this.client.from("suggested_plans").select("*").eq("user_id", user.value).eq("resulting_brew_id", brewId).is("deleted_at", null).order("updated_at", { ascending: false }).limit(1).maybeSingle(); if (error) return mapPostgrestError(error); return data ? this.mapped(data) : { ok: true, value: null }; }
  async list(): Promise<RemoteResult<SuggestedBrewPlan[]>> { const user = await this.userId(); if (!user.ok) return user; return this.rows(this.client.from("suggested_plans").select("*").eq("user_id", user.value).is("deleted_at", null).order("updated_at", { ascending: false })); }
  async listBySourceBrewId(brewId: string): Promise<RemoteResult<SuggestedBrewPlan[]>> { const user = await this.userId(); if (!user.ok) return user; return this.rows(this.client.from("suggested_plans").select("*").eq("user_id", user.value).eq("source_brew_id", brewId).is("deleted_at", null).order("updated_at", { ascending: false })); }
  async updateIfRevision(plan: SuggestedBrewPlan, expectedRevision: number): Promise<RemoteResult<SuggestedBrewPlan>> { const user = await this.userId(); if (!user.ok) return user; const { data, error } = await this.client.from("suggested_plans").update(toSuggestedPlanUpdate(plan, expectedRevision + 1)).eq("user_id", user.value).eq("id", plan.id).eq("revision", expectedRevision).is("deleted_at", null).select("*").maybeSingle(); if (error) return mapPostgrestError(error); return data ? this.mapped(data) : remoteFailure("revision_conflict", "The cloud Suggested Plan changed before this write completed."); }
  async update(plan: SuggestedBrewPlan): Promise<RemoteResult<SuggestedBrewPlan>> { const current = await this.getById(plan.id); if (!current.ok) return current; if (!current.value || current.revision === undefined) return remoteFailure("not_found", "Cloud Suggested Plan was not found."); return this.updateIfRevision(plan, current.revision); }
  async markUsed(planId: string, resultingBrewId: string, usedAt: string): Promise<RemoteResult<SuggestedBrewPlan>> { const current = await this.getById(planId); if (!current.ok) return current; if (!current.value) return remoteFailure("not_found", "Cloud Suggested Plan was not found."); return this.update({ ...current.value, status: "used", resultingBrewId, usedAt, updatedAt: usedAt }); }
  async upsertMany(plans: SuggestedBrewPlan[], idPrefix: string): Promise<RemoteResult<SuggestedBrewPlan[]>> { const saved: SuggestedBrewPlan[] = []; for (const plan of plans) { if (!plan.id.startsWith(idPrefix)) return remoteFailure("invalid_data", "Suggested Plan ID is outside the requested prefix."); const existing = await this.getById(plan.id); if (!existing.ok) return existing; const result = existing.value ? await this.update(plan) : await this.create(plan); if (!result.ok) return result; saved.push(result.value); } return { ok: true, value: saved }; }
  async removeByIdPrefix(idPrefix: string): Promise<RemoteResult<number>> { const all = await this.list(); if (!all.ok) return all; const user = await this.userId(); if (!user.ok) return user; let removed = 0; for (const plan of all.value.filter((item) => item.id.startsWith(idPrefix))) { const current = await this.getById(plan.id); if (!current.ok) return current; if (!current.value || current.revision === undefined) continue; const now = new Date().toISOString(); const { data, error } = await this.client.from("suggested_plans").update({ deleted_at: now, updated_at: now, revision: current.revision + 1 }).eq("user_id", user.value).eq("id", plan.id).eq("revision", current.revision).is("deleted_at", null).select("id").maybeSingle(); if (error) return mapPostgrestError(error); if (!data) return remoteFailure("revision_conflict", "The cloud Suggested Plan changed before deletion."); removed++; } return { ok: true, value: removed }; }
}
