"use client";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { UserProfile } from "@/domain";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import type { Database, Tables } from "@/types/database.types";
import type { OnboardingDraft, StoredUserProfile } from "@/repositories/user-profile-repository";
import { fromProfileRow, toProfileInsert } from "./mappers/profile-mapper";
import { mapPostgrestError, mapRepositoryException, remoteFailure } from "./repository-errors";
import type { RemoteMigrationRecord, RemoteResult, RemoteUserProfileRepository } from "./remote-repository-contracts";

export class SupabaseUserProfileRepository implements RemoteUserProfileRepository {
  constructor(private readonly client: SupabaseClient<Database> = getSupabaseBrowserClient()) {}
  private async userId(): Promise<RemoteResult<string>> { const { data, error } = await this.client.auth.getUser(); return error || !data.user ? remoteFailure("unauthenticated", "Sign in is required for cloud persistence.") : { ok: true, value: data.user.id }; }
  private mapped(row: Tables<"profiles">): RemoteResult<StoredUserProfile> { try { const value = fromProfileRow(row); return { ok: true, value: { profile: value.entity, selectedNeeds: value.entity.currentNeeds, onboardingCompleted: value.onboardingCompleted }, revision: value.revision }; } catch (error) { return mapRepositoryException(error); } }
  async load(): Promise<RemoteResult<StoredUserProfile | null>> { const user = await this.userId(); if (!user.ok) return user; const { data, error } = await this.client.from("profiles").select("*").eq("id", user.value).is("deleted_at", null).maybeSingle(); if (error) return mapPostgrestError(error); return data ? this.mapped(data) : { ok: true, value: null }; }
  async getForMigration():Promise<RemoteResult<RemoteMigrationRecord<StoredUserProfile>>>{const user=await this.userId();if(!user.ok)return user;const{data,error}=await this.client.from("profiles").select("*").eq("id",user.value).maybeSingle();if(error)return mapPostgrestError(error);if(!data)return{ok:true,value:{state:"missing"}};if(data.deleted_at)return{ok:true,value:{state:"deleted",revision:data.revision}};const mapped=this.mapped(data);return mapped.ok?{ok:true,value:{state:"active",entity:mapped.value,revision:mapped.revision??data.revision}}:{ok:true,value:{state:"invalid"}}}
  async save(draft: Required<OnboardingDraft>): Promise<RemoteResult<StoredUserProfile>> { const current = await this.load(); if (!current.ok) return current; const user = await this.userId(); if (!user.ok) return user; const now = new Date().toISOString(); const profile: UserProfile = { id: user.value, displayName: draft.displayName.trim(), experienceLevel: draft.experienceLevel, currentNeeds: draft.selectedNeeds, createdAt: current.value?.profile.createdAt ?? now, updatedAt: now }; if (current.value && current.revision !== undefined) return this.updateIfRevision({ profile, selectedNeeds: draft.selectedNeeds, onboardingCompleted: true }, current.revision); const { data, error } = await this.client.from("profiles").insert(toProfileInsert(profile, { onboardingCompleted: true })).select("*").single(); return error ? mapPostgrestError(error) : this.mapped(data); }
  async updateIfRevision(stored: StoredUserProfile, expectedRevision: number): Promise<RemoteResult<StoredUserProfile>> { const user = await this.userId(); if (!user.ok) return user; if (stored.profile.id !== user.value) return remoteFailure("permission_denied", "Profile ownership cannot be changed."); const insert = toProfileInsert(stored.profile, { onboardingCompleted: stored.onboardingCompleted, revision: expectedRevision + 1 }); const { id: _id, created_at: _createdAt, ...update } = insert; void _id; void _createdAt; const { data, error } = await this.client.from("profiles").update(update).eq("id", user.value).eq("revision", expectedRevision).is("deleted_at", null).select("*").maybeSingle(); if (error) return mapPostgrestError(error); return data ? this.mapped(data) : remoteFailure("revision_conflict", "The cloud Profile changed before this write completed."); }
  async remove(): Promise<RemoteResult<null>> { const current = await this.load(); if (!current.ok) return current; if (!current.value || current.revision === undefined) return { ok: true, value: null }; const user = await this.userId(); if (!user.ok) return user; const now = new Date().toISOString(); const { data, error } = await this.client.from("profiles").update({ deleted_at: now, updated_at: now, revision: current.revision + 1 }).eq("id", user.value).eq("revision", current.revision).is("deleted_at", null).select("id").maybeSingle(); if (error) return mapPostgrestError(error); return data ? { ok: true, value: null } : remoteFailure("revision_conflict", "The cloud Profile changed before deletion."); }
}
