import Link from "next/link";
import type { Brew } from "@/domain";
import { formatSuggestedPlanAdjustmentSummary, type SourceBrewSuggestedPlanProjection } from "@/application/suggested-plan-projection";

export function BrewSuggestedPlanContext({ brew, sourceProjection }: { brew: Brew; sourceProjection: SourceBrewSuggestedPlanProjection }) {
  const handoff = brew.suggestedPlanHandoff;
  if (brew.sourceType === "suggested_plan") return <section className="detail-section next-try-context"><p className="eyebrow">Started from Suggested Plan</p><h2>{handoff?.description ?? "Legacy Next Try"}</h2><p className="adjustment-summary">{formatSuggestedPlanAdjustmentSummary(handoff)}</p><dl className="detail-grid"><div><dt>Decision</dt><dd>{handoff?.userDecision ?? "Review required"}</dd></div><div><dt>Source Plan</dt><dd>{brew.sourceSuggestedPlanId ?? "Unavailable"}</dd></div><div><dt>Source Brew</dt><dd>{brew.sourceBrewId ?? "Unavailable"}</dd></div></dl><div className="form-actions">{brew.sourceSuggestedPlanId ? <Link className="secondary-button" href={`/plans/${brew.sourceSuggestedPlanId}`}>View Source Plan</Link> : <span className="unavailable-note">Source Plan unavailable</span>}{brew.sourceBrewId ? <Link className="text-button" href={`/journal/${brew.sourceBrewId}`}>View Source Brew</Link> : <span className="unavailable-note">Source Brew unavailable</span>}</div></section>;
  if (!sourceProjection.hasSuggestedPlans || !sourceProjection.latestPlan || !sourceProjection.latestAction) return null;
  const more = sourceProjection.totalPlans - 1;
  return <section className="detail-section source-next-try"><div className="section-heading"><div><p className="eyebrow">Next Try</p><h2>{sourceProjection.latestPlan.title}</h2></div><span>{sourceProjection.latestExecutionProjection?.label}</span></div><p className="adjustment-summary">{sourceProjection.latestAdjustmentSummary}</p><dl className="detail-grid"><div><dt>Created</dt><dd>{new Date(sourceProjection.latestPlan.createdAt).toLocaleString()}</dd></div><div><dt>Plan lifecycle</dt><dd>{sourceProjection.latestPlan.status}</dd></div><div><dt>Resulting Brew</dt><dd>{sourceProjection.latestExecutionProjection?.label ?? "Unavailable"}</dd></div>{sourceProjection.latestHandoffDecision && <div><dt>Decision</dt><dd>{sourceProjection.latestHandoffDecision.replaceAll("_", " ")}</dd></div>}</dl>{sourceProjection.latestExecutionProjection?.isRepairRequired && <p className="warning-note">This Plan and its resulting Brew need repair.</p>}{sourceProjection.hasPartialDataWarning && <p className="notice">Some Next Try links could not be loaded.</p>}<div className="source-next-try-actions"><Link className="secondary-button" href={sourceProjection.latestAction.href}>{sourceProjection.latestAction.label}</Link>{more > 0 && <Link className="text-button" href={`/journal/${brew.id}/plans`}>View all Next Tries <span>+{more} more</span></Link>}</div></section>;
}
