"use client";
import Link from "next/link";
import { FormEvent, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Brew, QuickPrepareInput } from "@/domain";
import { BrewService } from "@/application/brew-service";
import { LocalBrewRepository } from "@/repositories/local-brew-repository";
type Fields={coffeeDose:string;waterTotal:string;waterTemperature:string;dripper:string;grindSetting:string;beanName:string;equipmentNotes:string;userGoal:string};
type State={status:"loading"}|{status:"missing"}|{status:"ready";brew:Brew;error?:string};
const empty:Fields={coffeeDose:"",waterTotal:"",waterTemperature:"",dripper:"",grindSetting:"",beanName:"",equipmentNotes:"",userGoal:""};
function values(b:Brew):Fields{return{coffeeDose:String(b.recipeSnapshot.doseGrams.value),waterTotal:String(b.recipeSnapshot.totalWaterGrams.value),waterTemperature:String(b.recipeSnapshot.temperatureCelsius.value),dripper:b.recipeSnapshot.dripper.value,grindSetting:b.recipeSnapshot.grindDescription?.value??"",beanName:b.recipeSnapshot.bean?.name??"",equipmentNotes:b.recipeSnapshot.equipment?.notes??"",userGoal:b.recipeSnapshot.userGoal??""}}
export function DraftPrepareForm({brewId}:{brewId:string}){
 const router=useRouter(),lock=useRef(false),defaults=useRef<Fields>(empty);const[state,setState]=useState<State>({status:"loading"});const[fields,setFields]=useState<Fields>(empty);
 useEffect(()=>{const timer=window.setTimeout(()=>{const r=new LocalBrewRepository().getById(brewId);if(!r.value){setState({status:"missing"});return}const initial=values(r.value);defaults.current=initial;setFields(initial);setState({status:"ready",brew:r.value})},0);return()=>window.clearTimeout(timer)},[brewId]);
 function set(key:keyof Fields,value:string){setFields(current=>({...current,[key]:value}))}
 function reset(){setFields(current=>({...current,coffeeDose:defaults.current.coffeeDose,waterTotal:defaults.current.waterTotal,waterTemperature:defaults.current.waterTemperature,dripper:defaults.current.dripper,grindSetting:defaults.current.grindSetting}))}
 if(state.status==="loading")return <main className="route-loading"><h1>Loading preparation…</h1></main>;
 if(state.status==="missing")return <main className="state-page"><h1>Brew draft not found.</h1><Link className="primary-button" href="/brew">Back to Brew</Link></main>;
 const brew=state.brew,handoff=brew.suggestedPlanHandoff;
 if(brew.executionStatus!=="not_started")return <main className="state-page"><h1>{brew.executionStatus==="completed"?"This Brew is complete.":"This Brew has already started."}</h1><Link className="primary-button" href={brew.executionStatus==="completed"?`/journal/${brew.id}`:`/brew/${brew.id}`}>Continue</Link></main>;
 function submit(event:FormEvent){event.preventDefault();if(lock.current)return;lock.current=true;const input:QuickPrepareInput={recipeVersionId:String(brew.recipeSnapshot.sourceRecipeVersion??1),coffeeDose:Number(fields.coffeeDose),waterTotal:Number(fields.waterTotal),waterTemperature:Number(fields.waterTemperature),dripper:fields.dripper,grindSetting:fields.grindSetting,beanName:fields.beanName,equipmentNotes:fields.equipmentNotes,userGoal:fields.userGoal};const result=new BrewService(new LocalBrewRepository()).confirmDraftPrepare(brew.id,input);if(result.ok)router.push(`/brew/${brew.id}`);else{setState({status:"ready",brew:result.latest??brew,error:result.message});lock.current=false}}
 const rows:Array<[keyof Fields,string,string?]>=[["coffeeDose","Coffee Dose","g"],["waterTotal","Water Total","g"],["waterTemperature","Water Temperature","°C"],["dripper","Dripper"],["grindSetting","Grind Setting"]];
 return <main className="prepare-page"><div className="prepare-topbar"><Link className="back-link" href={brew.sourceSuggestedPlanId?`/plans/${brew.sourceSuggestedPlanId}`:"/brew"}>←</Link><h1>Prepare</h1><span/></div><section className="prepare-recipe"><p className="eyebrow">Brew Draft</p><h2>{brew.recipeSnapshot.title}</h2></section>{handoff&&<section className="next-try-review"><p className="eyebrow">Next Try · confirmation required</p><h2>{handoff.variable.replaceAll("_"," ")}</h2><div><span>Original <strong>{String(handoff.originalValue)}{handoff.unit}</strong></span><span>→</span><span>Suggested <strong>{String(handoff.suggestedValue)}{handoff.unit}</strong></span></div><p>{handoff.rationale}</p><p>{handoff.confidence} confidence</p><strong>Only one main variable is suggested for this next try.</strong><p>You can keep this suggestion or adjust it before brewing.</p></section>}<form onSubmit={submit}>{state.error&&<p role="alert" className="form-error">{state.error}</p>}<section className="prepare-parameters"><div className="section-heading"><h2>Confirm final values</h2><button className="reset-button" type="button" onClick={reset}>{handoff?"Reset to Suggested Plan":"Reset Recipe Parameters"}</button></div>{rows.map(([key,label,suffix])=><label className="prepare-field" key={key}><span>{label}</span><div className="input-with-suffix"><input value={fields[key]} onChange={e=>set(key,e.target.value)} type={suffix?"number":"text"}/>{suffix&&<span>{suffix}</span>}</div><small>Final value saved to this Brew Snapshot</small></label>)}</section><section className="prepare-optional"><h2>Optional details</h2><label className="prepare-field"><span>Bean</span><input value={fields.beanName} onChange={e=>set("beanName",e.target.value)}/></label><label className="prepare-field"><span>Equipment Notes</span><textarea value={fields.equipmentNotes} onChange={e=>set("equipmentNotes",e.target.value)}/></label></section><div className="prepare-submit"><span>{handoff?"Review complete":"Draft update"}</span><button className="primary-button" type="submit">Confirm &amp; Continue</button></div></form></main>;
}
