"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Brew, FlavorFeedbackInput, FlavorNote, FlavorOverallImpression, FlavorRating } from "@/domain";
import { flavorFeedbackInputSchema, flavorNoteOptions } from "@/domain";
import { BrewService, type BrewDomainErrorCode } from "@/application/brew-service";
import { LocalBrewRepository } from "@/repositories/local-brew-repository";

type LoadState = { status: "loading" } | { status: "missing"; message: string } | { status: "blocked"; brew: Brew } | { status: "ready"; brew: Brew };
type RatingKey = "acidity" | "sweetness" | "bitterness" | "body" | "clarity" | "aftertaste" | "balance";
const ratingFields: Array<{ key: RatingKey; label: string }> = [{ key: "acidity", label: "酸度" }, { key: "sweetness", label: "甜度" }, { key: "bitterness", label: "苦味" }, { key: "body", label: "醇厚度" }, { key: "clarity", label: "乾淨度" }, { key: "aftertaste", label: "餘韻" }, { key: "balance", label: "平衡" }];
const impressions: Array<{ value: FlavorOverallImpression; label: string }> = [{ value: "liked", label: "喜歡" }, { value: "neutral", label: "普通" }, { value: "disliked", label: "不喜歡" }];
const errorCopy: Partial<Record<BrewDomainErrorCode, string>> = { brew_not_found: "找不到這筆 Brew。", invalid_execution_status: "完成沖煮後才能補充風味回饋。", invalid_feedback: "請檢查標示的回饋欄位。", persistence_failed: "無法保存回饋，請確認瀏覽器允許本地儲存後重試。", already_skipped: "這筆回饋已標記為稍後再填。" };

export function FlavorFeedbackForm({ brewId }: { brewId: string }) {
  const router = useRouter(); const lock = useRef(false);
  const [state, setState] = useState<LoadState>({ status: "loading" });
  const [overallImpression, setOverallImpression] = useState<FlavorOverallImpression | undefined>();
  const [ratings, setRatings] = useState<Partial<Record<RatingKey, FlavorRating>>>({});
  const [notes, setNotes] = useState<FlavorNote[]>([]); const [freeformNotes, setFreeformNotes] = useState("");
  const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { const result = new BrewService(new LocalBrewRepository()).getFlavorFeedback(brewId); if (!result.ok) { setState({ status: "missing", message: errorCopy[result.code] ?? result.message }); return; } if (result.brew.executionStatus !== "completed") { setState({ status: "blocked", brew: result.brew }); return; } const feedback = result.value; setState({ status: "ready", brew: result.brew }); if (feedback) { setOverallImpression(feedback.overallImpression); setRatings(Object.fromEntries(ratingFields.flatMap(({ key }) => feedback[key] ? [[key, feedback[key]]] : []))); setNotes(feedback.flavorNotes); setFreeformNotes(feedback.freeformNotes ?? ""); } }, 0); return () => window.clearTimeout(timer); }, [brewId]);
  function toggleNote(note: FlavorNote) { setNotes((current) => current.includes(note) ? current.filter((item) => item !== note) : [...current, note]); }
  function submit() { if (lock.current || state.status !== "ready") return; if (!overallImpression) { setError("請選擇整體感受。"); return; } const input: FlavorFeedbackInput = { overallImpression, ...ratings, flavorNotes: notes, ...(freeformNotes.trim() && { freeformNotes: freeformNotes.trim() }) }; const parsed = flavorFeedbackInputSchema.safeParse(input); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "請檢查回饋內容。"); return; } lock.current = true; setSaving(true); const result = new BrewService(new LocalBrewRepository()).upsertFlavorFeedback(brewId, parsed.data); if (result.ok) router.replace(`/journal/${brewId}`); else { setState({ status: "ready", brew: result.latest ?? state.brew }); setError(errorCopy[result.code] ?? result.message); lock.current = false; setSaving(false); } }
  function skip() { if (lock.current || state.status !== "ready") return; lock.current = true; setSaving(true); const result = new BrewService(new LocalBrewRepository()).skipFlavorFeedback(brewId); if (result.ok || result.code === "already_skipped") router.replace(`/journal/${brewId}`); else { setError(errorCopy[result.code] ?? result.message); lock.current = false; setSaving(false); } }
  if (state.status === "loading") return <main className="route-loading"><p className="eyebrow">Flavor Feedback</p><h1>Loading your cup…</h1></main>;
  if (state.status === "missing") return <main className="state-page"><p className="eyebrow">Flavor Feedback</p><h1>This Brew could not be found.</h1><p>{state.message}</p><Link className="primary-button" href="/journal">Back to Journal</Link></main>;
  if (state.status === "blocked") return <main className="state-page"><p className="eyebrow">Flavor Feedback</p><h1>完成沖煮後才能補充風味回饋</h1><p>目前 Brew 狀態是 {state.brew.executionStatus.replace("_", " ")}。</p><div className="form-actions"><Link className="primary-button" href={`/brew/${brewId}`}>Back to Brew</Link><Link className="secondary-button" href="/journal">Journal</Link></div></main>;
  const feedback = state.brew.flavorFeedback;
  return <main className="feedback-page"><div className="summary-topbar"><Link aria-label="Back to Brew Detail" className="back-link" href={`/journal/${brewId}`}>←</Link><h1>Flavor Feedback</h1><span /></div><section className="feedback-identity"><h2>{state.brew.recipeSnapshot.title}</h2><p>{state.brew.recipeSnapshot.bean?.name ?? "未記錄咖啡豆"} · {new Date(state.brew.completedAt ?? state.brew.updatedAt).toLocaleDateString()}</p></section>{error && <p className="form-error" role="alert">{error}</p>}<fieldset className="feedback-section"><legend>整體感受 <span>必填</span></legend><div className="impression-options">{impressions.map((item) => <label key={item.value}><input checked={overallImpression === item.value} name="overall-impression" onChange={() => { setOverallImpression(item.value); setError(undefined); }} type="radio" value={item.value} /><span>{item.label}</span></label>)}</div></fieldset><section className="feedback-section"><h2>風味強度 <span>選填 · 1 很低，5 很高</span></h2><div className="rating-grid">{ratingFields.map((field) => <fieldset key={field.key}><legend>{field.label}</legend><div>{([1,2,3,4,5] as FlavorRating[]).map((value) => <label key={value}><input checked={ratings[field.key] === value} name={field.key} onChange={() => setRatings((current) => ({ ...current, [field.key]: value }))} type="radio" value={value} /><span>{value}</span></label>)}</div></fieldset>)}</div></section><fieldset className="feedback-section"><legend>Flavor Notes <span>選填，可多選</span></legend><div className="flavor-note-grid">{flavorNoteOptions.map((item) => <label key={item.value}><input checked={notes.includes(item.value)} onChange={() => toggleNote(item.value)} type="checkbox" /><span>{item.label}</span></label>)}</div></fieldset><section className="feedback-section"><label className="notes-label" htmlFor="feedback-notes">Additional Notes <span>選填</span></label><textarea id="feedback-notes" maxLength={500} onChange={(event) => setFreeformNotes(event.target.value)} rows={5} value={freeformNotes} /><p className="character-count">{freeformNotes.length}/500</p><p className="feedback-boundary">這是你的主觀風味紀錄；AI Analysis 可在之後另行要求。</p></section><div className="feedback-actions"><button className="primary-button" disabled={saving} onClick={submit} type="button">{saving ? "Saving…" : feedback ? "Update Feedback" : "Save Feedback"}</button><button className="text-button" disabled={saving} onClick={skip} type="button">Skip for now</button></div></main>;
}
