"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Brew, RecipeStep } from "@/domain";
import { formatDuration } from "@/domain";
import { BrewService, type BrewDomainErrorCode } from "@/application/brew-service";
import { BrewSessionCoordinator } from "@/application/brew-session-coordinator";
import { SuggestedPlanService } from "@/application/suggested-plan-service";
import { LocalBrewRepository } from "@/repositories/local-brew-repository";
import { LocalSuggestedPlanRepository } from "@/repositories/local-suggested-plan-repository";
import { BrewTimers } from "./brew-timers";

type ViewState = { status: "loading" } | { status: "found"; brew: Brew; notice?: string; errorCode?: BrewDomainErrorCode } | { status: "missing"; message?: string };
const errorCopy: Partial<Record<BrewDomainErrorCode, string>> = {
  brew_not_found: "找不到這筆 Brew。它可能已被刪除或只存在於另一個瀏覽器。",
  invalid_execution_status: "這筆 Brew 目前不是可開始或推進的狀態。資料不會被重置。",
  no_stages: "這筆 Brew 沒有可用的 Snapshot 階段，無法開始引導。",
  invalid_stage_order: "目前階段資料不一致，已保留最新 Brew 狀態。",
  duplicate_stage_completion: "這個階段已經被推進，已重新載入最新資料。",
  stages_incomplete: "仍有必要沖煮階段尚未完成。",
  already_completed: "這杯已完成，可繼續查看 Brew Complete。",
  already_saved: "這杯已保存到 Journal。",
  invalid_quick_rating: "快速感受選項無效。",
  persistence_failed: "無法保存 Brew。請檢查瀏覽器儲存空間後重試。",
};
function expectedStart(steps: RecipeStep[], index: number) { return steps.slice(0, index).reduce((total, step) => total + (step.durationSeconds ?? 0), 0); }

export function LiveBrewDraft({ brewId }: { brewId: string }) {
  const [state, setState] = useState<ViewState>({ status: "loading" }); const [syncWarning,setSyncWarning]=useState<string|null>(null);const actionLock = useRef(false); const [acting, setActing] = useState(false); const router = useRouter();
  useEffect(() => { const timer = window.setTimeout(() => { const result = new LocalBrewRepository().getById(brewId); if (result.value){setState({ status: "found", brew: result.value, ...((result.ok ? result.notice : result.message) && { notice: result.ok ? result.notice : result.message }) });if(result.value.sourceSuggestedPlanId&&result.value.startedAt){const plan=new LocalSuggestedPlanRepository().getById(result.value.sourceSuggestedPlanId).value;if(!plan||plan.status!=="used"||plan.usedAt!==result.value.startedAt||plan.resultingBrewId!==result.value.id)setSyncWarning("Brew started, but the Next Try status could not be synced.")}} else setState({ status: "missing", ...(!result.ok && { message: result.message }) }); }, 0); return () => window.clearTimeout(timer); }, [brewId]);
  function applyAction(action: (service: BrewService) => ReturnType<BrewService["startBrewSession"]>) { if (actionLock.current) return; actionLock.current = true; setActing(true); const result = action(new BrewService(new LocalBrewRepository())); if (result.ok) setState({ status: "found", brew: result.value, ...(result.resumed && { notice: "Brew 已在進行中；已依原始時間恢復，沒有重設 startedAt。" }) }); else if (result.code === "brew_not_found") setState({ status: "missing", message: errorCopy[result.code] }); else setState({ status: "found", brew: result.latest ?? (state.status === "found" ? state.brew : result.latest!), notice: errorCopy[result.code], errorCode: result.code }); actionLock.current = false; setActing(false); }
  if (state.status === "loading") return <main className="live-loading" aria-live="polite"><p className="eyebrow">Live Brew</p><h1>Loading your Brew draft…</h1></main>;
  if (state.status === "missing") return <main className="state-page"><p className="eyebrow">Brew not found</p><h1>This draft is not available.</h1><p>{state.message ?? "It may have been removed, or this link belongs to another browser."}</p><div className="form-actions"><Link className="primary-button" href="/discover">Back to Discover</Link><Link className="secondary-button" href="/journal">Back to Journal</Link></div></main>;
  const { brew } = state; const snapshot = brew.recipeSnapshot; const steps = [...snapshot.steps].sort((a, b) => a.order - b.order); const current = steps[brew.currentStageOrder]; const allStagesDone = brew.currentStageOrder >= steps.length && steps.length > 0; const previousTarget = brew.currentStageOrder > 0 ? steps[brew.currentStageOrder - 1]?.targetWaterGrams ?? 0 : 0; const targetPour = current ? Math.max(0, current.targetWaterGrams - previousTarget) : null; const startSeconds = current ? expectedStart(steps, brew.currentStageOrder) : 0;
  const startSession=()=>{if(actionLock.current)return;actionLock.current=true;setActing(true);const brews=new LocalBrewRepository(),plans=new LocalSuggestedPlanRepository(),result=new BrewSessionCoordinator(new BrewService(brews),new SuggestedPlanService(brews,plans)).startBrewSessionWithSuggestedPlanSync(brew.id);if(result.ok){setState({status:"found",brew:result.brew});setSyncWarning(result.suggestedPlanSync.status==="failed"?"Brew started, but the Next Try status could not be synced.":null)}else setState({status:"found",brew,notice:result.message,errorCode:"persistence_failed"});actionLock.current=false;setActing(false)};
  const retrySync=()=>{if(actionLock.current)return;actionLock.current=true;setActing(true);const result=new SuggestedPlanService(new LocalBrewRepository(),new LocalSuggestedPlanRepository()).syncSuggestedPlanUsageFromBrew(brew.id);setSyncWarning(result.ok?null:`${result.message} The Brew remains in progress.`);if(result.ok)setState({status:"found",brew,notice:"Next Try status synced."});actionLock.current=false;setActing(false)};
  const completeStage = () => applyAction((service) => service.completeCurrentStage(brew.id, brew.currentStageOrder));
  const completeBrew = () => { if (actionLock.current) return; actionLock.current = true; setActing(true); const result = new BrewService(new LocalBrewRepository()).completeBrewSession(brew.id); if (result.ok) router.push(`/brew/${brew.id}/complete`); else { setState({ status: "found", brew: result.latest ?? brew, notice: errorCopy[result.code], errorCode: result.code }); actionLock.current = false; setActing(false); } };
  if(brew.sourceType==="suggested_plan"&&brew.suggestedPlanHandoff?.userDecision==="pending")return <main className="state-page"><p className="eyebrow">Next Try needs confirmation</p><h1>Review this adjustment before brewing.</h1><p>{brew.suggestedPlanHandoff.description}</p><p><strong>{String(brew.suggestedPlanHandoff.originalValue)}{brew.suggestedPlanHandoff.unit}</strong> → <strong>{String(brew.suggestedPlanHandoff.suggestedValue)}{brew.suggestedPlanHandoff.unit}</strong></p><Link className="primary-button" href={`/brew/${brew.id}/prepare`}>Review Next Try</Link></main>;
  if (steps.length === 0) return <main className="state-page"><p className="eyebrow">Brew data issue</p><h1>This Brew has no stages.</h1><p>Start is unavailable because the immutable Recipe Snapshot has no guidance steps.</p><div className="form-actions"><Link className="primary-button" href={`/recipes/${brew.sourceRecipeId}`}>Recipe Detail</Link><Link className="secondary-button" href="/discover">Discover</Link></div></main>;
  return <main className="live-page"><div className="live-topbar"><Link aria-label="Back to Quick Prepare" className="back-link" href={`/recipes/${brew.sourceRecipeId}/prepare`}>←</Link><h1>Live Brew</h1><span className="draft-mark">{brew.executionStatus === "in_progress" ? "In progress" : "Draft"}</span></div>{state.notice && <p className="notice" role={state.errorCode ? "alert" : "status"}>{state.notice}</p>}{brew.suggestedPlanHandoff&&brew.suggestedPlanHandoff.userDecision!=="pending"&&<aside className="next-try-live"><strong>Next Try · {brew.suggestedPlanHandoff.userDecision==="accepted"?"Accepted":"Adjusted before brew"}</strong><span>Suggested: {String(brew.suggestedPlanHandoff.suggestedValue)}{brew.suggestedPlanHandoff.unit}</span></aside>}{syncWarning&&<aside className="sync-warning" role="status"><p>{syncWarning} Timer and stages continue normally; do not start again.</p><button className="secondary-button" disabled={acting} onClick={retrySync} type="button">Retry Sync</button></aside>}
    <section className="live-metrics"><div><span>Water Temp</span><strong>{snapshot.temperatureCelsius.value}°C</strong></div><div><span>Target Weight</span><strong>{current?.targetWaterGrams ?? snapshot.totalWaterGrams.value}g</strong></div><div><span>Target Time</span><strong>{formatDuration(brew.brewPlan.expectedTotalTime)}</strong></div></section>
    {(brew.executionStatus === "in_progress" || brew.executionStatus === "completed") && <BrewTimers accumulatedPauseSeconds={brew.accumulatedPauseSeconds} completedSeconds={brew.actualTotalTimeSeconds} currentStageStartedAt={brew.currentStageStartedAt} running={brew.executionStatus === "in_progress"} startedAt={brew.startedAt} />}
    <section className="live-focus"><p className="eyebrow">{snapshot.title}</p>{allStagesDone ? <div className="all-stages-done" role="status"><strong>所有沖煮階段已完成</strong><p>下一輪將提供 Brew Complete 與結果保存。</p></div> : <><div className="pour-visual" aria-label={`${current?.pattern ?? "guided"} pour pattern preview`}><span>{current?.pattern?.replace("_", " ") ?? "guided pour"}</span></div><strong className="target-weight">{current?.targetWaterGrams ?? 0}g</strong><h2>{current?.title ?? "Stage unavailable"}</h2><p>{current?.instruction ?? "No instruction is available for this stage."}</p><dl className="current-stage-details"><div><dt>Step type</dt><dd>{current?.pattern?.replace("_", " ") ?? "Not specified"}</dd></div><div><dt>Target pour</dt><dd>{targetPour === null ? "—" : `${targetPour}g`}</dd></div><div><dt>Expected start</dt><dd>{formatDuration(startSeconds)}</dd></div><div><dt>Expected duration</dt><dd>{current?.durationSeconds ? formatDuration(current.durationSeconds) : "—"}</dd></div></dl></>}</section>
    <section className="live-stages" aria-live="polite"><div className="section-heading"><div><p className="eyebrow">Stages</p><h2>Full brew plan</h2></div><span>{allStagesDone ? "Stages complete" : brew.executionStatus.replace("_", " ")}</span></div><ol>{steps.map((stage, index) => { const saved = brew.stageResults.find((result) => result.stageOrder === index); const status = saved ? "completed" : index === brew.currentStageOrder ? "current" : "upcoming"; return <li aria-current={status === "current" ? "step" : undefined} className={`stage-${status}`} key={stage.id}><span aria-hidden="true">{saved ? "✓" : index + 1}</span><span><strong>{stage.title}</strong><small>{saved ? `Completed · ${formatDuration(saved.actualDurationSeconds)}` : status === "current" ? "Current stage" : "Not started"}</small></span><span>{stage.targetWaterGrams}g</span><span>{stage.durationSeconds ? formatDuration(stage.durationSeconds) : "—"}</span></li>; })}</ol></section>
    <section className="live-summary"><div><strong>—</strong><span>Current</span></div><div><strong>{snapshot.totalWaterGrams.value}g</strong><span>Target</span></div><div><strong>—</strong><span>Remaining</span></div></section>
    <p className="leave-note">沖煮仍在進行時可離開此頁；返回後會依保存的 timestamp 繼續顯示。</p>
    <section className="session-upcoming">{brew.executionStatus === "not_started" ? <button className="primary-button" disabled={acting} onClick={startSession} type="button">{acting ? "Starting…" : state.errorCode ? "Retry Start Brew Session" : "Start Brew Session"}</button> : brew.executionStatus === "in_progress" && !allStagesDone ? <button className="primary-button" disabled={acting} onClick={completeStage} type="button">{acting ? "Saving Stage…" : "Complete Stage"}</button> : brew.executionStatus === "in_progress" && allStagesDone ? <button className="primary-button" disabled={acting} onClick={completeBrew} type="button">{acting ? "Completing Brew…" : state.errorCode ? "Retry Brew Complete" : "Continue to Brew Complete"}</button> : brew.executionStatus === "completed" ? <Link className="primary-button" href={`/brew/${brew.id}/complete`}>View Brew Complete</Link> : <p className="notice">This Brew is {brew.executionStatus}; this round will not reset or transition it.</p>}</section>
  </main>;
}
