"use client";
import { useState } from "react";
import Link from "next/link";
import { useAuth } from "./auth-provider";
import { createMigrationRepositoryBundle, getRuntimeRepositoryBundle, RUNTIME_REPOSITORY_MODE } from "@/infrastructure/repositories/repository-composition";
import { CloudMigrationRemoteGateway } from "@/infrastructure/supabase/cloud-migration-remote-gateway";
import { migrationFaultPoints, type MigrationFaultPoint } from "@/infrastructure/supabase/fault-injecting-cloud-migration-remote-gateway";
import { MigrationRemotePreflightService, type MigrationRemotePreflight } from "@/application/migration-remote-preflight-service";
import { MigrationReviewService } from "@/application/migration-review-service";
import { CloudMigrationCheckpointRepository } from "@/repositories/cloud-migration-checkpoint-repository";
import { DemoSeedService } from "@/dev/demo-seed-service";

type LocalSummary = { profile: boolean; brews: number; plans: number; valid: boolean };
const seedService = () => { const bundle = getRuntimeRepositoryBundle(); return new DemoSeedService(bundle.userProfileRepository, bundle.brewRepository, bundle.suggestedPlanRepository, "development"); };
export function MigrationQaPanel() {
  const auth = useAuth(), userId = auth.status === "authenticated" ? auth.user?.id : null;
  const [local, setLocal] = useState<LocalSummary | null>(null), [remote, setRemote] = useState<MigrationRemotePreflight | null>(null), [checkpoint, setCheckpoint] = useState<ReturnType<CloudMigrationCheckpointRepository["getForCurrentUser"]> | null>(null);
  const [message, setMessage] = useState("Diagnostics are read-only until a Local seed/reset action is explicitly selected."), [confirmSmokeReset, setConfirmSmokeReset] = useState(false), [confirmCheckpointReset, setConfirmCheckpointReset] = useState(false), [fault, setFault] = useState<MigrationFaultPoint | "off">("off");
  async function refresh() { const review = await new MigrationReviewService(getRuntimeRepositoryBundle()).review(); setLocal({ profile: review.summary.profile === 1, brews: review.summary.brews, plans: review.summary.suggestedPlans, valid: review.validation.valid }); if (userId) setCheckpoint(new CloudMigrationCheckpointRepository().getForCurrentUser(userId)); setMessage("Local and checkpoint diagnostics refreshed. No migration was started."); }
  async function preflight() { const bundle = await createMigrationRepositoryBundle(); if (!bundle.ok) { setMessage(bundle.message); setRemote(null); return; } const result = await new MigrationRemotePreflightService(bundle.value.local, new CloudMigrationRemoteGateway(bundle.value.remote)).collect(); if (!result.ok) { setMessage(result.message); setRemote(null); return; } setRemote(result.value); setMessage(result.value.canStart ? "Remote preflight passed. Start Migration remains available only on /migration." : "Remote conflict found. Migration must not start."); }
  function seed() { const result = seedService().seed("migration_smoke", { overwriteProfile: true }); setMessage(result.ok ? `Seeded ${result.brewCount} Local Brews and ${result.planCount} Local Plan. No remote data was touched.` : result.message); void refresh(); }
  function resetSmoke() { if (!confirmSmokeReset) { setConfirmSmokeReset(true); setMessage("Confirm removal of only migration-smoke- Local Brew and Plan records."); return; } const result = seedService().resetMigrationSmoke(); setConfirmSmokeReset(false); setMessage(result.ok ? `Removed ${result.removedBrews} smoke Brews and ${result.removedPlans} smoke Plans. Profile and remote data were preserved.` : result.message); void refresh(); }
  function resetCheckpoint() { if (!userId) { setMessage("Sign in before inspecting or resetting a checkpoint."); return; } if (!confirmCheckpointReset) { setConfirmCheckpointReset(true); setMessage("Confirm checkpoint-only reset for the current authenticated account."); return; } const result = new CloudMigrationCheckpointRepository().removeForCurrentUser(userId); setConfirmCheckpointReset(false); setMessage(result.ok ? "Current account checkpoint removed. Local and remote entities were preserved." : result.message); void refresh(); }
  const cp = checkpoint?.ok ? checkpoint.value : null;
  return <main className="demo-page migration-qa"><p className="eyebrow">Development tools only</p><h1>Migration Smoke QA</h1><p>No page-load migration, sync, or remote write occurs here. Real migration remains behind consent and Start Migration on <Link href="/migration">/migration</Link>.</p><dl className="demo-counts"><div><dt>Authenticated</dt><dd>{auth.status === "authenticated" ? "Yes" : "No"}</dd></div><div><dt>Runtime repository</dt><dd>{RUNTIME_REPOSITORY_MODE}</dd></div><div><dt>Sync</dt><dd>Not implemented</dd></div></dl><p className="notice" role="status">{message}</p>
  <section><h2>Local smoke graph</h2><button className="secondary-button" onClick={() => void refresh()} type="button">Refresh diagnostics</button><dl className="demo-counts"><div><dt>Profile</dt><dd>{local ? local.profile ? "Present" : "Missing" : "Not checked"}</dd></div><div><dt>Brews</dt><dd>{local?.brews ?? "—"}</dd></div><div><dt>Plans</dt><dd>{local?.plans ?? "—"}</dd></div><div><dt>Graph</dt><dd>{local ? local.valid ? "Valid" : "Invalid" : "Not checked"}</dd></div></dl><div className="demo-actions"><button className="primary-button" onClick={seed} type="button">Seed Migration Smoke Graph</button><button className="warning-button" onClick={resetSmoke} type="button">{confirmSmokeReset ? "Confirm smoke Local reset" : "Reset Migration Smoke Local Data"}</button></div></section>
  <section><h2>Remote preflight</h2><button className="secondary-button" onClick={() => void preflight()} type="button">Run read-only preflight</button>{remote ? <><dl className="demo-counts"><div><dt>Profile</dt><dd>{remote.profile}</dd></div><div><dt>Brews missing / matching / conflict</dt><dd>{remote.brews.missing} / {remote.brews.matching} / {remote.brews.conflict}</dd></div><div><dt>Plans missing / matching / conflict</dt><dd>{remote.suggestedPlans.missing} / {remote.suggestedPlans.matching} / {remote.suggestedPlans.conflict}</dd></div><div><dt>Start safety</dt><dd>{remote.canStart ? "Clear" : "Blocked"}</dd></div></dl><p>Deleted and invalid rows: {remote.brews.deleted + remote.suggestedPlans.deleted} deleted; {remote.brews.invalid + remote.suggestedPlans.invalid} invalid.</p></> : <p>Not checked.</p>}</section>
  <section><h2>Checkpoint inspector</h2><dl className="demo-counts"><div><dt>Status</dt><dd>{cp?.status ?? "none"}</dd></div><div><dt>Attempts</dt><dd>{cp?.attemptCount ?? 0}</dd></div><div><dt>Brews / Plans</dt><dd>{cp ? `${cp.migratedBrewIds.length} / ${cp.migratedSuggestedPlanIds.length}` : "0 / 0"}</dd></div><div><dt>Patched references</dt><dd>{cp ? cp.patchedBrewIds.length + cp.patchedSuggestedPlanIds.length : 0}</dd></div><div><dt>Graph verified</dt><dd>{cp?.graphVerified ? "Yes" : "No"}</dd></div><div><dt>Error</dt><dd>{cp?.errorCode ?? "none"}</dd></div></dl><button className="warning-button" disabled={!userId} onClick={resetCheckpoint} type="button">{confirmCheckpointReset ? "Confirm checkpoint-only reset" : "Reset Migration Smoke Checkpoint"}</button></section>
  <section><h2>Failure injection harness</h2><label htmlFor="fault-point">Controlled test point</label><select id="fault-point" onChange={(event) => setFault(event.target.value as MigrationFaultPoint | "off")} value={fault}><option value="off">Off</option>{migrationFaultPoints.map((point) => <option key={point} value={point}>{point}</option>)}</select><p>Selected: {fault}. The decorator is integration-test only and is never connected to production migration from this page.</p></section></main>;
}
