import{describe,expect,it}from"vitest";import{BrewService}from"./brew-service";import{createBrewDraft,createQuickPrepareDefaults}from"./brew-factory";import{brewRecordDetailsInputSchema,calculateNumericDifference,formatSignedNumber,normalizeBrewRecordDetailsInput}from"@/domain";import{recipeFixtures}from"@/data/fixtures/recipes";import{LOCAL_BREW_KEY,LocalBrewRepository}from"@/repositories/local-brew-repository";
class MemoryStorage{values=new Map<string,string>();failWrites=false;getItem(k:string){return this.values.get(k)??null}setItem(k:string,v:string){if(this.failWrites)throw new Error("quota");this.values.set(k,v)}}
function setup(status:"completed"|"in_progress"="completed"){const storage=new MemoryStorage(),repository=new LocalBrewRepository(storage);const base=createBrewDraft(recipeFixtures[0],createQuickPrepareDefaults(recipeFixtures[0]),{now:()=>"2026-07-18T00:00:00.000Z",createId:()=>"brew-1"});repository.createDraft({...base,executionStatus:status,completedAt:status==="completed"?"2026-07-18T00:03:00.000Z":null});return{storage,repository}}
const input={bean:{name:"  Kenya AA  "},equipment:{grinderSetting:"  24 clicks  "},actualDoseGrams:20.5,actualWaterGrams:305,actualTemperatureCelsius:93,notes:"  clean cup  "};
describe("Brew record details",()=>{
it("adds to completed Brew",()=>{const{repository}=setup();expect(new BrewService(repository).upsertBrewRecordDetails("brew-1",input).ok).toBe(true)});it("rejects in progress",()=>expect(new BrewService(setup("in_progress").repository).upsertBrewRecordDetails("brew-1",input)).toMatchObject({ok:false,code:"invalid_execution_status"}));it("returns not found",()=>expect(new BrewService(new LocalBrewRepository(new MemoryStorage())).upsertBrewRecordDetails("missing",input)).toMatchObject({ok:false,code:"brew_not_found"}));
it("normalizes all empty to null",()=>expect(normalizeBrewRecordDetailsInput({bean:{name:" "},equipment:{grinder:""},notes:""})).toBeNull());it("saves Bean Name alone",()=>expect(normalizeBrewRecordDetailsInput({bean:{name:"Kenya"}})?.bean).toEqual({name:"Kenya"}));it("saves Grinder Setting alone",()=>expect(normalizeBrewRecordDetailsInput({equipment:{grinderSetting:"24"}})?.equipment).toEqual({grinderSetting:"24"}));it("accepts decimal actual dose",()=>expect(brewRecordDetailsInputSchema.safeParse({actualDoseGrams:20.5}).success).toBe(true));it("rejects invalid actual values",()=>{expect(brewRecordDetailsInputSchema.safeParse({actualDoseGrams:0}).success).toBe(false);expect(brewRecordDetailsInputSchema.safeParse({actualWaterGrams:2001}).success).toBe(false);expect(brewRecordDetailsInputSchema.safeParse({actualTemperatureCelsius:111}).success).toBe(false)});it("trims text and empty objects",()=>expect(normalizeBrewRecordDetailsInput(input)).toMatchObject({bean:{name:"Kenya AA"},equipment:{grinderSetting:"24 clicks"},notes:"clean cup"}));it("validates note length and future roast date",()=>{expect(brewRecordDetailsInputSchema.safeParse({notes:"x".repeat(1001)}).success).toBe(false);expect(brewRecordDetailsInputSchema.safeParse({bean:{roastDate:"2999-01-01"}}).success).toBe(false)});
it("creates and preserves timestamps",()=>{const{repository}=setup();let result=new BrewService(repository,{now:()=>"2026-07-18T01:00:00.000Z"}).upsertBrewRecordDetails("brew-1",input);if(!result.ok)throw new Error(result.message);result=new BrewService(repository,{now:()=>"2026-07-18T02:00:00.000Z"}).upsertBrewRecordDetails("brew-1",{bean:{name:"Ethiopia"}});if(!result.ok)throw new Error(result.message);expect(result.value.recordDetails).toMatchObject({createdAt:"2026-07-18T01:00:00.000Z",updatedAt:"2026-07-18T02:00:00.000Z"})});
it("preserves immutable and independent state",()=>{const{repository}=setup();const before=repository.getById("brew-1").value!;const result=new BrewService(repository).upsertBrewRecordDetails("brew-1",input);if(!result.ok)throw new Error(result.message);expect(result.value.recipeSnapshot).toEqual(before.recipeSnapshot);expect(result.value.brewPlan).toEqual(before.brewPlan);expect(result.value.stageResults).toEqual(before.stageResults);expect(result.value.flavorFeedback).toEqual(before.flavorFeedback);expect(result.value).toMatchObject({feedbackStatus:before.feedbackStatus,analysisStatus:before.analysisStatus,recordStatus:before.recordStatus})});
it("does not copy targets into actual",()=>{const{repository}=setup();const result=new BrewService(repository).upsertBrewRecordDetails("brew-1",{bean:{name:"Kenya"}});expect(result.ok&&result.value.recordDetails?.actualDoseGrams).toBeNull();expect(result.ok&&result.value.recordDetails?.actualWaterGrams).toBeNull();expect(result.ok&&result.value.recordDetails?.actualTemperatureCelsius).toBeNull()});
it("migrates legacy data and reloads details",()=>{const{storage,repository}=setup();const legacy={...repository.getById("brew-1").value!};delete(legacy as Partial<typeof legacy>).recordDetails;storage.values.set(LOCAL_BREW_KEY,JSON.stringify({version:1,data:{brews:[legacy]}}));expect(new LocalBrewRepository(storage).getById("brew-1").value?.recordDetails).toBeNull();new BrewService(new LocalBrewRepository(storage)).upsertBrewRecordDetails("brew-1",input);expect(new LocalBrewRepository(storage).getById("brew-1").value?.recordDetails?.bean?.name).toBe("Kenya AA")});it("clears details to null",()=>{const{repository}=setup();const service=new BrewService(repository);service.upsertBrewRecordDetails("brew-1",input);const result=service.upsertBrewRecordDetails("brew-1",{});expect(result.ok&&result.value.recordDetails).toBeNull()});it("calculates and formats differences",()=>{expect(calculateNumericDifference(20.5,20)).toBe(.5);expect(formatSignedNumber(.5,"g")).toBe("+0.5g");expect(formatSignedNumber(-8,"g")).toBe("-8g");expect(formatSignedNumber(null,"g")).toBe("—")});it("maps persistence failure",()=>{const{storage,repository}=setup();storage.failWrites=true;expect(new BrewService(repository).upsertBrewRecordDetails("brew-1",input)).toMatchObject({ok:false,code:"persistence_failed"})});
});
