import { describe, expect, it } from "vitest";
import { createBrewDraft, createQuickPrepareDefaults } from "./brew-factory";
import { BrewService } from "./brew-service";
import { recipeFixtures } from "@/data/fixtures/recipes";
import { LocalBrewRepository } from "@/repositories/local-brew-repository";

class MemoryStorage { values = new Map<string, string>(); failWrites = false; getItem(key: string) { return this.values.get(key) ?? null; } setItem(key: string, value: string) { if (this.failWrites) throw new Error("quota"); this.values.set(key, value); } }
const recipe = recipeFixtures[0];
function draft(id = "brew-1") { return createBrewDraft(recipe, createQuickPrepareDefaults(recipe), { now: () => "2026-07-18T00:00:00.000Z", createId: () => id }); }
function setup(id = "brew-1") { const storage = new MemoryStorage(); const repository = new LocalBrewRepository(storage); repository.createDraft(draft(id)); return { storage, repository }; }
function latestId(service: BrewService) { const result = service.getLatestInProgressBrew(); if (!result.ok) throw new Error(result.message); return result.value?.id; }

describe("BrewService lifecycle", () => {
  it("transitions not_started to in_progress", () => { const { repository } = setup(); const result = new BrewService(repository, { now: () => "2026-07-18T00:00:05.000Z" }).startBrewSession("brew-1"); expect(result.ok && result.value.executionStatus).toBe("in_progress"); });
  it("does not reset startedAt for an in_progress Brew", () => { const { repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T00:00:05.000Z" }).startBrewSession("brew-1"); const result = new BrewService(repository, { now: () => "2026-07-18T00:10:00.000Z" }).startBrewSession("brew-1"); expect(result.ok && result.value.startedAt).toBe("2026-07-18T00:00:05.000Z"); });
  it("returns brew_not_found", () => expect(new BrewService(new LocalBrewRepository(new MemoryStorage())).startBrewSession("missing")).toMatchObject({ ok: false, code: "brew_not_found" }));
  it("does not start without Snapshot stages", () => { const { repository } = setup(); const value = repository.getById("brew-1").value!; repository.updateDraft({ ...value, recipeSnapshot: { ...value.recipeSnapshot, steps: [] } }); expect(new BrewService(repository).startBrewSession("brew-1")).toMatchObject({ ok: false, code: "no_stages" }); });
  it("writes startedAt", () => { const { repository } = setup(); const result = new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); expect(result.ok && result.value.startedAt).toBe("2026-07-18T01:00:00.000Z"); });
  it("writes currentStageStartedAt", () => { const { repository } = setup(); const result = new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); expect(result.ok && result.value.currentStageStartedAt).toBe("2026-07-18T01:00:00.000Z"); });
  it("creates a Stage Result", () => { const { repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); const result = new BrewService(repository, { now: () => "2026-07-18T01:00:12.000Z" }).completeCurrentStage("brew-1", 0); expect(result.ok && result.value.stageResults).toHaveLength(1); });
  it("keeps actualWeight null", () => { const { repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); const result = new BrewService(repository, { now: () => "2026-07-18T01:00:12.000Z" }).completeCurrentStage("brew-1", 0); expect(result.ok && result.value.stageResults[0].actualWeight).toBeNull(); });
  it("does not write target into actual fields", () => { const { repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); const result = new BrewService(repository, { now: () => "2026-07-18T01:00:12.000Z" }).completeCurrentStage("brew-1", 0); expect(result.ok && result.value.stageResults[0].weightDifference).toBeNull(); });
  it("calculates actualDurationSeconds", () => { const { repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); const result = new BrewService(repository, { now: () => "2026-07-18T01:00:12.000Z" }).completeCurrentStage("brew-1", 0); expect(result.ok && result.value.stageResults[0].actualDurationSeconds).toBe(12); });
  it("increments currentStageOrder", () => { const { repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); const result = new BrewService(repository, { now: () => "2026-07-18T01:00:12.000Z" }).completeCurrentStage("brew-1", 0); expect(result.ok && result.value.currentStageOrder).toBe(1); });
  it("starts the next stage at completion time", () => { const { repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); const result = new BrewService(repository, { now: () => "2026-07-18T01:00:12.000Z" }).completeCurrentStage("brew-1", 0); expect(result.ok && result.value.currentStageStartedAt).toBe("2026-07-18T01:00:12.000Z"); });
  it("keeps execution in_progress after a stage", () => { const { repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); const result = new BrewService(repository, { now: () => "2026-07-18T01:00:12.000Z" }).completeCurrentStage("brew-1", 0); expect(result.ok && result.value.executionStatus).toBe("in_progress"); });
  it("rejects stale duplicate completion", () => { const { repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); const service = new BrewService(repository, { now: () => "2026-07-18T01:00:12.000Z" }); service.completeCurrentStage("brew-1", 0); expect(service.completeCurrentStage("brew-1", 0)).toMatchObject({ ok: false, code: "duplicate_stage_completion" }); });
  it("rejects invalid stage order", () => { const { repository } = setup(); const service = new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }); const started = service.startBrewSession("brew-1"); if (!started.ok) throw new Error("setup failed"); repository.updateDraft({ ...started.value, currentStageOrder: started.value.recipeSnapshot.steps.length }); expect(service.completeCurrentStage("brew-1")).toMatchObject({ ok: false, code: "invalid_stage_order" }); });
  it("does not mark completed after the last stage", () => { const { repository } = setup(); let current = new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); if (!current.ok) throw new Error("setup failed"); const count = current.value.recipeSnapshot.steps.length; for (let index = 0; index < count; index += 1) current = new BrewService(repository, { now: () => `2026-07-18T01:0${index + 1}:00.000Z` }).completeCurrentStage("brew-1", index); if (!current.ok) throw new Error(current.message); expect(current.value.currentStageOrder).toBe(count); expect(current.value.executionStatus).toBe("in_progress"); });
  it("maps repository update failure to persistence_failed", () => { const { storage, repository } = setup(); storage.failWrites = true; expect(new BrewService(repository).startBrewSession("brew-1")).toMatchObject({ ok: false, code: "persistence_failed" }); });
  it("recovers timestamps through a new repository instance", () => { const { storage, repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); expect(new LocalBrewRepository(storage).getById("brew-1").value?.startedAt).toBe("2026-07-18T01:00:00.000Z"); });
  it("does not duplicate saved stageResults", () => { const { repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); const service = new BrewService(repository, { now: () => "2026-07-18T01:00:12.000Z" }); service.completeCurrentStage("brew-1", 0); service.completeCurrentStage("brew-1", 0); expect(repository.getById("brew-1").value?.stageResults).toHaveLength(1); });
  it("finds the latest in-progress Brew", () => { const { repository } = setup(); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); expect(latestId(new BrewService(repository))).toBe("brew-1"); });
  it("chooses deterministically among multiple in-progress Brews", () => { const { repository } = setup(); repository.createDraft(draft("brew-2")); new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession("brew-1"); new BrewService(repository, { now: () => "2026-07-18T02:00:00.000Z" }).startBrewSession("brew-2"); expect(latestId(new BrewService(repository))).toBe("brew-2"); });
  it("returns null when no Brew is in progress", () => expect(new BrewService(setup().repository).getLatestInProgressBrew()).toMatchObject({ ok: true, value: null }));
});
