import { describe, expect, it } from "vitest";
import { createBrewDraft, createQuickPrepareDefaults } from "./brew-factory";
import { BrewService } from "./brew-service";
import { recipeFixtures } from "@/data/fixtures/recipes";
import { calculateStageDurationDifference, formatOptionalWeightDifference, formatSignedDuration } from "@/domain";
import { LocalBrewRepository } from "@/repositories/local-brew-repository";

class MemoryStorage { values = new Map<string, string>(); failWrites = false; getItem(key: string) { return this.values.get(key) ?? null; } setItem(key: string, value: string) { if (this.failWrites) throw new Error("quota"); this.values.set(key, value); } }
const recipe = recipeFixtures[0];
function draft(id = "brew-1") { return createBrewDraft(recipe, createQuickPrepareDefaults(recipe), { now: () => "2026-07-18T01:00:00.000Z", createId: () => id }); }
function setup(id = "brew-1") { const storage = new MemoryStorage(); const repository = new LocalBrewRepository(storage); repository.createDraft(draft(id)); return { storage, repository }; }
function stagesReady(repository: LocalBrewRepository, id = "brew-1") { let result = new BrewService(repository, { now: () => "2026-07-18T01:00:00.000Z" }).startBrewSession(id); if (!result.ok) throw new Error(result.message); for (let index = 0; index < result.value.recipeSnapshot.steps.length; index += 1) { result = new BrewService(repository, { now: () => `2026-07-18T01:00:${String((index + 1) * 10).padStart(2, "0")}.000Z` }).completeCurrentStage(id, index); if (!result.ok) throw new Error(result.message); } return result.value; }
function complete(repository: LocalBrewRepository, id = "brew-1", now = "2026-07-18T01:00:30.000Z") { stagesReady(repository, id); return new BrewService(repository, { now: () => now }).completeBrewSession(id); }

describe("Brew completion, Journal, and historical projection", () => {
  it("completes after every stage", () => { const { repository } = setup(); expect(complete(repository)).toMatchObject({ ok: true, value: { executionStatus: "completed" } }); });
  it("rejects incomplete stages", () => { const { repository } = setup(); new BrewService(repository).startBrewSession("brew-1"); expect(new BrewService(repository).completeBrewSession("brew-1")).toMatchObject({ ok: false, code: "stages_incomplete" }); });
  it("returns brew_not_found for completion", () => expect(new BrewService(new LocalBrewRepository(new MemoryStorage())).completeBrewSession("missing")).toMatchObject({ ok: false, code: "brew_not_found" }));
  it("rejects completion outside in_progress", () => { const { repository } = setup(); expect(new BrewService(repository).completeBrewSession("brew-1")).toMatchObject({ ok: false, code: "invalid_execution_status" }); });
  it("writes completedAt", () => { const { repository } = setup(); const result = complete(repository); expect(result.ok && result.value.completedAt).toBe("2026-07-18T01:00:30.000Z"); });
  it("calculates actualTotalTimeSeconds", () => { const { repository } = setup(); const result = complete(repository); expect(result.ok && result.value.actualTotalTimeSeconds).toBe(30); });
  it("deducts accumulatedPauseSeconds", () => { const { repository } = setup(); const ready = stagesReady(repository); repository.updateDraft({ ...ready, accumulatedPauseSeconds: 5 }); const result = new BrewService(repository, { now: () => "2026-07-18T01:00:30.000Z" }).completeBrewSession("brew-1"); expect(result.ok && result.value.actualTotalTimeSeconds).toBe(25); });
  it("clears currentStageStartedAt", () => { const { repository } = setup(); const result = complete(repository); expect(result.ok && result.value.currentStageStartedAt).toBeNull(); });
  it("sets executionStatus completed", () => { const { repository } = setup(); const result = complete(repository); expect(result.ok && result.value.executionStatus).toBe("completed"); });
  it("keeps recordStatus draft", () => { const { repository } = setup(); const result = complete(repository); expect(result.ok && result.value.recordStatus).toBe("draft"); });
  it("keeps analysis not_requested", () => { const { repository } = setup(); const result = complete(repository); expect(result.ok && result.value.analysisStatus).toBe("not_requested"); });
  it("keeps actualTotalWater null", () => { const { repository } = setup(); const result = complete(repository); expect(result.ok && result.value.actualTotalWater).toBeNull(); });
  it("never copies target water into actual water", () => { const { repository } = setup(); const result = complete(repository); expect(result.ok && result.value.actualTotalWater).not.toBe(recipe.currentVersion.totalWaterGrams); });
  it("does not recreate completedAt on duplicate completion", () => { const { repository } = setup(); const first = complete(repository); const second = new BrewService(repository, { now: () => "2026-07-18T02:00:00.000Z" }).completeBrewSession("brew-1"); expect(second).toMatchObject({ ok: false, code: "already_completed" }); expect(repository.getById("brew-1").value?.completedAt).toBe(first.ok ? first.value.completedAt : null); });
  it("keeps the completed timer value fixed", () => { const { repository } = setup(); complete(repository); const stored = repository.getById("brew-1").value; expect(stored?.actualTotalTimeSeconds).toBe(30); expect(new BrewService(repository, { now: () => "2026-07-19T01:00:00.000Z" }).completeBrewSession("brew-1")).toMatchObject({ ok: false, code: "already_completed" }); expect(repository.getById("brew-1").value?.actualTotalTimeSeconds).toBe(30); });
  it("saves a completed Brew", () => { const { repository } = setup(); complete(repository); const result = new BrewService(repository).saveCompletedBrew("brew-1"); expect(result.ok && result.value.recordStatus).toBe("saved"); });
  it("saves without completed Flavor Feedback", () => { const { repository } = setup(); complete(repository); const result = new BrewService(repository).saveCompletedBrew("brew-1"); expect(result.ok && result.value.feedbackStatus).toBe("awaiting_feedback"); });
  it("saves without Bean", () => { const { repository } = setup(); complete(repository); const result = new BrewService(repository).saveCompletedBrew("brew-1"); expect(result.ok && result.value.recipeSnapshot.bean).toBeUndefined(); });
  it("saves without Equipment metadata", () => { const { repository } = setup(); complete(repository); const result = new BrewService(repository).saveCompletedBrew("brew-1"); expect(result.ok && result.value.recipeSnapshot.equipment).toBeUndefined(); });
  it("saves a legal quick rating", () => { const { repository } = setup(); complete(repository); const result = new BrewService(repository).saveCompletedBrew("brew-1", { quickRating: "liked" }); expect(result.ok && result.value.quickRating).toBe("liked"); });
  it("rejects an illegal quick rating", () => { const { repository } = setup(); complete(repository); expect(new BrewService(repository).saveCompletedBrew("brew-1", { quickRating: "excellent" })).toMatchObject({ ok: false, code: "invalid_quick_rating" }); });
  it("maps an explicit skipped feeling to skipped feedback", () => { const { repository } = setup(); complete(repository); const result = new BrewService(repository).saveCompletedBrew("brew-1", { quickRating: "skipped" }); expect(result.ok && result.value.feedbackStatus).toBe("skipped"); });
  it("saves without a quick rating", () => { const { repository } = setup(); complete(repository); const result = new BrewService(repository).saveCompletedBrew("brew-1"); expect(result.ok && result.value.quickRating).toBeUndefined(); });
  it("does not update an already saved Brew", () => { const { repository } = setup(); complete(repository); new BrewService(repository).saveCompletedBrew("brew-1"); expect(new BrewService(repository).saveCompletedBrew("brew-1")).toMatchObject({ ok: false, code: "already_saved" }); });
  it("maps completion persistence failure", () => { const { storage, repository } = setup(); stagesReady(repository); storage.failWrites = true; expect(new BrewService(repository).completeBrewSession("brew-1")).toMatchObject({ ok: false, code: "persistence_failed" }); });
  it("maps save persistence failure", () => { const { storage, repository } = setup(); complete(repository); storage.failWrites = true; expect(new BrewService(repository).saveCompletedBrew("brew-1")).toMatchObject({ ok: false, code: "persistence_failed" }); });
  it("Journal excludes unfinished Brews", () => { const { repository } = setup(); expect(repository.listJournalEntries().value).toHaveLength(0); });
  it("sorts Journal by completedAt descending", () => { const { repository } = setup(); repository.createDraft(draft("brew-2")); complete(repository, "brew-1", "2026-07-18T02:00:00.000Z"); complete(repository, "brew-2", "2026-07-18T03:00:00.000Z"); expect(repository.listJournalEntries().value.map((item) => item.id)).toEqual(["brew-2", "brew-1"]); });
  it("keeps completed drafts visible", () => { const { repository } = setup(); complete(repository); expect(repository.listJournalEntries().value[0].recordStatus).toBe("draft"); });
  it("shows saved Brews in Journal", () => { const { repository } = setup(); complete(repository); new BrewService(repository).saveCompletedBrew("brew-1"); expect(repository.listJournalEntries().value[0].recordStatus).toBe("saved"); });
  it("projects the same Brew id instead of creating a Journal copy", () => { const { repository } = setup(); complete(repository); expect(repository.listJournalEntries().value[0].id).toBe(repository.getById("brew-1").value?.id); });
  it("Brew Detail data comes from the Snapshot", () => { const { repository } = setup(); complete(repository); expect(repository.getById("brew-1").value?.recipeSnapshot.title).toBe(recipe.currentVersion.title); });
  it("source Recipe changes do not alter Brew Detail history", () => { const copy = structuredClone(recipe); const storage = new MemoryStorage(); const repository = new LocalBrewRepository(storage); repository.createDraft(createBrewDraft(copy, createQuickPrepareDefaults(copy), { now: () => "2026-07-18T01:00:00.000Z", createId: () => "history" })); copy.currentVersion.title = "Changed later"; expect(repository.getById("history").value?.recipeSnapshot.title).not.toBe("Changed later"); });
  it("calculates stage duration differences", () => expect(calculateStageDurationDifference(47, 45)).toBe(2));
  it("formats missing actual weight safely", () => expect(formatOptionalWeightDifference(null, 40)).toBe("—"));
  it("recovers completed drafts after reload", () => { const { storage, repository } = setup(); complete(repository); expect(new LocalBrewRepository(storage).getById("brew-1").value).toMatchObject({ executionStatus: "completed", recordStatus: "draft" }); });
  it("recovers saved Brews after reload", () => { const { storage, repository } = setup(); complete(repository); new BrewService(repository).saveCompletedBrew("brew-1"); expect(new LocalBrewRepository(storage).getById("brew-1").value?.recordStatus).toBe("saved"); });
  it("returns null for a missing Brew Detail id", () => expect(new LocalBrewRepository(new MemoryStorage()).getById("missing").value).toBeNull());
  it("formats signed time differences", () => { expect(formatSignedDuration(2)).toBe("+0:02"); expect(formatSignedDuration(-3)).toBe("-0:03"); expect(formatSignedDuration(0)).toBe("0:00"); });
});
