import { describe, expect, it } from "vitest";
import { createBrewDraft, createQuickPrepareDefaults } from "./brew-factory";
import { BrewService } from "./brew-service";
import { flavorFeedbackInputSchema } from "@/domain";
import { recipeFixtures } from "@/data/fixtures/recipes";
import { LocalBrewRepository, LOCAL_BREW_KEY } from "@/repositories/local-brew-repository";

class MemoryStorage { values = new Map<string,string>(); failWrites = false; getItem(key:string) { return this.values.get(key) ?? null; } setItem(key:string,value:string) { if (this.failWrites) throw new Error("quota"); this.values.set(key,value); } }
const input = { overallImpression: "liked" as const, acidity: 4 as const, flavorNotes: ["clean" as const], freeformNotes: "  Bright cup  " };
function setup(status: "completed" | "in_progress" = "completed") { const storage = new MemoryStorage(); const repository = new LocalBrewRepository(storage); const draft = createBrewDraft(recipeFixtures[0], createQuickPrepareDefaults(recipeFixtures[0]), { now:()=>"2026-07-18T00:00:00.000Z", createId:()=>"brew-1" }); repository.createDraft({ ...draft, executionStatus:status, completedAt:status === "completed" ? "2026-07-18T00:03:00.000Z" : null, feedbackStatus:status === "completed" ? "awaiting_feedback" : "not_requested" }); return { storage, repository }; }
describe("Flavor Feedback", () => {
  it("adds feedback to a completed Brew",()=>{ const {repository}=setup(); const result=new BrewService(repository,{now:()=>"2026-07-18T01:00:00.000Z",createId:()=>"feedback-1"}).upsertFlavorFeedback("brew-1",input); expect(result.ok && result.value.flavorFeedback?.id).toBe("feedback-1"); });
  it("rejects an in-progress Brew",()=>expect(new BrewService(setup("in_progress").repository).upsertFlavorFeedback("brew-1",input)).toMatchObject({ok:false,code:"invalid_execution_status"}));
  it("returns brew_not_found",()=>expect(new BrewService(new LocalBrewRepository(new MemoryStorage())).upsertFlavorFeedback("missing",input)).toMatchObject({ok:false,code:"brew_not_found"}));
  it("validates overall impression",()=>expect(flavorFeedbackInputSchema.safeParse({...input,overallImpression:"great"}).success).toBe(false));
  it("validates rating range and integers",()=>{ expect(flavorFeedbackInputSchema.safeParse({...input,acidity:6}).success).toBe(false); expect(flavorFeedbackInputSchema.safeParse({...input,acidity:2.5}).success).toBe(false); });
  it("validates flavor note union and duplicates",()=>{ expect(flavorFeedbackInputSchema.safeParse({...input,flavorNotes:["invented"]}).success).toBe(false); expect(flavorFeedbackInputSchema.safeParse({...input,flavorNotes:["clean","clean"]}).success).toBe(false); });
  it("validates notes length",()=>expect(flavorFeedbackInputSchema.safeParse({...input,freeformNotes:"x".repeat(501)}).success).toBe(false));
  it("creates timestamps and completes feedback without changing other statuses",()=>{ const {repository}=setup(); const result=new BrewService(repository,{now:()=>"2026-07-18T01:00:00.000Z",createId:()=>"feedback-1"}).upsertFlavorFeedback("brew-1",input); if(!result.ok) throw new Error(result.message); expect(result.value.flavorFeedback).toMatchObject({createdAt:"2026-07-18T01:00:00.000Z",updatedAt:"2026-07-18T01:00:00.000Z",freeformNotes:"Bright cup"}); expect(result.value).toMatchObject({feedbackStatus:"completed",analysisStatus:"not_requested",recordStatus:"draft"}); });
  it("allows missing Bean and Equipment",()=>{ const {repository}=setup(); const result=new BrewService(repository).upsertFlavorFeedback("brew-1",input); expect(result.ok).toBe(true); });
  it("preserves id and createdAt while editing",()=>{ const {repository}=setup(); new BrewService(repository,{now:()=>"2026-07-18T01:00:00.000Z",createId:()=>"feedback-1"}).upsertFlavorFeedback("brew-1",input); const result=new BrewService(repository,{now:()=>"2026-07-18T02:00:00.000Z",createId:()=>"feedback-2"}).upsertFlavorFeedback("brew-1",{...input,overallImpression:"neutral"}); if(!result.ok) throw new Error(result.message); expect(result.value.flavorFeedback).toMatchObject({id:"feedback-1",createdAt:"2026-07-18T01:00:00.000Z",updatedAt:"2026-07-18T02:00:00.000Z",overallImpression:"neutral"}); });
  it("skips without creating feedback and can later add it",()=>{ const {repository}=setup(); const skipped=new BrewService(repository).skipFlavorFeedback("brew-1"); expect(skipped.ok && skipped.value).toMatchObject({feedbackStatus:"skipped",flavorFeedback:null}); const added=new BrewService(repository).upsertFlavorFeedback("brew-1",input); expect(added.ok && added.value.feedbackStatus).toBe("completed"); });
  it("persists feedback across repository reload",()=>{ const {storage,repository}=setup(); new BrewService(repository).upsertFlavorFeedback("brew-1",input); expect(new LocalBrewRepository(storage).getById("brew-1").value?.flavorFeedback?.overallImpression).toBe("liked"); });
  it("migrates old v1 data missing flavorFeedback",()=>{ const {storage,repository}=setup(); const brew=repository.getById("brew-1").value!; const legacy={...brew}; delete (legacy as Partial<typeof legacy>).flavorFeedback; storage.values.set(LOCAL_BREW_KEY,JSON.stringify({version:1,data:{brews:[legacy]}})); expect(new LocalBrewRepository(storage).getById("brew-1").value?.flavorFeedback).toBeNull(); });
  it("persists skipped across reload",()=>{ const {storage,repository}=setup(); new BrewService(repository).skipFlavorFeedback("brew-1"); expect(new LocalBrewRepository(storage).getById("brew-1").value?.feedbackStatus).toBe("skipped"); });
  it("maps persistence failure",()=>{ const {storage,repository}=setup(); storage.failWrites=true; expect(new BrewService(repository).upsertFlavorFeedback("brew-1",input)).toMatchObject({ok:false,code:"persistence_failed"}); });
});
