import{buildBrewReferencePatch,chunkMigrationIds,classifyProfileMigrationState,createReviewFingerprint,migrationEngineCheckpointSchema,sameMigrationEntity,toMigrationBaseBrew,validateLocalCloudMigrationGraph,type Brew,type MigrationEngineCheckpoint,type MigrationEngineErrorCode,type MigrationEngineResult,type StartCloudMigrationCommand,type SuggestedBrewPlan}from"@/domain";
import type{StoredUserProfile}from"@/repositories/user-profile-repository";
import type{LocalRepositoryBundle}from"@/infrastructure/repositories/repository-composition";import type{CloudMigrationGateway,GatewayResult}from"@/infrastructure/supabase/cloud-migration-remote-gateway";import type{RemoteMigrationRecord}from"@/infrastructure/supabase/remote-repository-contracts";import{CloudMigrationCheckpointRepository}from"@/repositories/cloud-migration-checkpoint-repository";import{MigrationReviewService}from"./migration-review-service";
type Clock=()=>string;type EntityType="profile"|"brew"|"suggested_plan"|"brew_patch"|"plan_patch"|"verification"|"checkpoint";
const done=(ids:string[],id:string)=>ids.includes(id)?ids:[...ids,id].sort();
export class LocalToCloudMigrationService{
 constructor(private readonly local:LocalRepositoryBundle,private readonly remote:CloudMigrationGateway,private readonly checkpoints:CloudMigrationCheckpointRepository,private readonly authenticatedUserId:string,private readonly now:Clock=()=>new Date().toISOString(),private readonly onProgress:(checkpoint:MigrationEngineCheckpoint)=>void=()=>{}){}
 async getStatus(){return this.checkpoints.getForCurrentUser(this.authenticatedUserId)}
 private failure(code:MigrationEngineErrorCode,message:string,checkpoint?:MigrationEngineCheckpoint,type:EntityType|null=null,id:string|null=null):MigrationEngineResult{if(!checkpoint)return{ok:false,code,message};const failed=migrationEngineCheckpointSchema.parse({...checkpoint,status:"failed",errorCode:code,failedEntityType:type,failedEntityId:id,lastAttemptAt:this.now()});const saved=this.checkpoints.update(failed);return saved.ok?{ok:false,code,message,checkpoint:failed}:{ok:false,code:"checkpoint_write_failed",message:"Migration stopped because progress could not be saved."}}
 private mapRemote<T>(result:GatewayResult<T>,checkpoint:MigrationEngineCheckpoint,type:EntityType,id:string|null):MigrationEngineResult|null{if(result.ok)return null;const code:MigrationEngineErrorCode=result.code==="unauthenticated"?"unauthenticated":result.code==="revision_conflict"?"revision_conflict":result.code==="invalid_data"?"remote_row_invalid":"remote_write_failed";return this.failure(code,"Cloud migration could not safely continue.",checkpoint,type,id)}
 private async collect(){const collected=await new MigrationReviewService(this.local).collectSummary();const graph=validateLocalCloudMigrationGraph(collected.graph);const fingerprint=createReviewFingerprint({profile:collected.graph.profile,brews:collected.graph.brews,suggestedPlans:collected.graph.suggestedPlans,recipeCount:collected.summary.recipes});return{...collected,validation:graph,fingerprint}}
 async prepare(command:StartCloudMigrationCommand){if(!command.consentConfirmed)return{ok:false as const,code:"consent_required" as const,message:"Confirm the migration review before starting."};const collected=await this.collect();if(command.reviewFingerprint!==collected.fingerprint)return{ok:false as const,code:"review_outdated" as const,message:"Local data changed. Review it again before migration."};if(!collected.validation.valid||!collected.graph.profile)return{ok:false as const,code:"local_data_invalid" as const,message:"Local data must pass review before migration."};return{ok:true as const,collected}}
 async start(command:StartCloudMigrationCommand):Promise<MigrationEngineResult>{const prepared=await this.prepare(command);if(!prepared.ok)return prepared;const existing=this.checkpoints.getForCurrentUser(this.authenticatedUserId);if(!existing.ok)return{ok:false,code:"checkpoint_invalid",message:existing.message};if(existing.value?.status==="completed")return{ok:false,code:"migration_already_completed",message:"This reviewed data was already migrated.",checkpoint:existing.value};if(existing.value&&existing.value.reviewFingerprint===command.reviewFingerprint)return this.run(existing.value,prepared.collected);if(existing.value&&existing.value.status!=="failed")return{ok:false,code:"review_outdated",message:"Local data changed. Review it again before migration."};const at=this.now(),checkpoint=migrationEngineCheckpointSchema.parse({version:1,userId:this.authenticatedUserId,reviewFingerprint:command.reviewFingerprint,status:"in_progress",startedAt:at,completedAt:null,lastAttemptAt:at,profileStatus:"pending",migratedBrewIds:[],migratedSuggestedPlanIds:[],patchedBrewIds:[],patchedSuggestedPlanIds:[],graphVerified:false,errorCode:null,failedEntityType:null,failedEntityId:null,attemptCount:1,totalBrewCount:prepared.collected.graph.brews.length,totalSuggestedPlanCount:prepared.collected.graph.suggestedPlans.length,totalBrewPatchCount:prepared.collected.graph.brews.filter(x=>x.sourceSuggestedPlanId).length,totalSuggestedPlanPatchCount:0});const saved=existing.value?this.checkpoints.update(checkpoint):this.checkpoints.create(checkpoint);if(saved.ok)this.onProgress(checkpoint);return saved.ok?this.run(checkpoint,prepared.collected):{ok:false,code:"checkpoint_write_failed",message:saved.message}}
 async retry():Promise<MigrationEngineResult>{const read=this.checkpoints.getForCurrentUser(this.authenticatedUserId);if(!read.ok||!read.value)return{ok:false,code:"checkpoint_invalid",message:"Migration progress is unavailable."};if(read.value.status==="completed")return{ok:false,code:"migration_already_completed",message:"Migration is already completed.",checkpoint:read.value};const collected=await this.collect();if(collected.fingerprint!==read.value.reviewFingerprint)return{ok:false,code:"review_outdated",message:"Local data changed. Return to Review.",checkpoint:read.value};const resumed=migrationEngineCheckpointSchema.parse({...read.value,status:"in_progress",errorCode:null,failedEntityType:null,failedEntityId:null,lastAttemptAt:this.now(),attemptCount:read.value.attemptCount+1});const saved=this.checkpoints.update(resumed);return saved.ok?this.run(resumed,collected):{ok:false,code:"checkpoint_write_failed",message:saved.message}}
 resume(){return this.retry()}
 private classifyRecord<T>(record:RemoteMigrationRecord<T>,local:T,base?:T){if(record.state==="missing")return"missing" as const;if(record.state==="deleted")return"deleted" as const;if(record.state==="invalid")return"invalid" as const;if(sameMigrationEntity(local,record.entity))return"matching" as const;if(base&&sameMigrationEntity(base,record.entity))return"base_matching" as const;return"conflict" as const}
 private async run(initial:MigrationEngineCheckpoint,collected:Awaited<ReturnType<LocalToCloudMigrationService["collect"]>>):Promise<MigrationEngineResult>{let cp=initial;const profile=collected.graph.profile as StoredUserProfile,brews=[...collected.graph.brews].sort((a,b)=>a.id.localeCompare(b.id)),plans=[...collected.graph.suggestedPlans].sort((a,b)=>a.id.localeCompare(b.id));
  const remoteProfile=await this.remote.readProfile();const mapped=this.mapRemote(remoteProfile,cp,"profile",null);if(mapped)return mapped;if(!remoteProfile.ok)return mapped!;const profileState=remoteProfile.value.state==="active"?classifyProfileMigrationState(profile,remoteProfile.value.entity):remoteProfile.value.state;
  if(profileState==="deleted")return this.failure("remote_entity_deleted","Cloud Profile was previously deleted.",cp,"profile");if(profileState==="invalid")return this.failure("remote_row_invalid","Cloud Profile is invalid.",cp,"profile");if(profileState==="profile_conflict")return this.failure("profile_conflict","Cloud Profile contains different user data.",cp,"profile");
  const brewStates=new Map<string,{record:RemoteMigrationRecord<Brew>;kind:string}>(),planStates=new Map<string,{record:RemoteMigrationRecord<SuggestedBrewPlan>;kind:string}>();for(const brew of brews){const r=await this.remote.readBrew(brew.id);const failure=this.mapRemote(r,cp,"brew",brew.id);if(failure)return failure;if(!r.ok)continue;const kind=this.classifyRecord(r.value,brew,toMigrationBaseBrew(brew));if(kind==="deleted")return this.failure("remote_entity_deleted","A Cloud Brew was previously deleted.",cp,"brew",brew.id);if(kind==="invalid")return this.failure("remote_row_invalid","A Cloud Brew is invalid.",cp,"brew",brew.id);if(kind==="conflict")return this.failure("remote_entity_conflict","A Cloud Brew has conflicting content.",cp,"brew",brew.id);brewStates.set(brew.id,{record:r.value,kind})}for(const plan of plans){const r=await this.remote.readPlan(plan.id);const failure=this.mapRemote(r,cp,"suggested_plan",plan.id);if(failure)return failure;if(!r.ok)continue;const kind=this.classifyRecord(r.value,plan);if(kind==="deleted")return this.failure("remote_entity_deleted","A Cloud Suggested Plan was previously deleted.",cp,"suggested_plan",plan.id);if(kind==="invalid")return this.failure("remote_row_invalid","A Cloud Suggested Plan is invalid.",cp,"suggested_plan",plan.id);if(kind==="conflict")return this.failure("remote_entity_conflict","A Cloud Suggested Plan has conflicting content.",cp,"suggested_plan",plan.id);planStates.set(plan.id,{record:r.value,kind})}
  if(cp.profileStatus==="pending"){let write:GatewayResult<StoredUserProfile>|null=null;if(profileState==="missing")write=await this.remote.createProfile({...profile,profile:{...profile.profile,id:this.authenticatedUserId}});else if(profileState==="bootstrap"&&remoteProfile.value.state==="active")write=await this.remote.updateProfile({...profile,profile:{...profile.profile,id:this.authenticatedUserId}},remoteProfile.value.revision);const failure=write?this.mapRemote(write,cp,"profile",null):null;if(failure)return failure;cp={...cp,profileStatus:profileState==="matching"?"already_present":"migrated"};const saved=this.checkpoints.update(cp);if(!saved.ok)return{ok:false,code:"checkpoint_write_failed",message:saved.message}}
  for(const batch of chunkMigrationIds(brews.map(x=>x.id))){for(const id of batch){if(cp.migratedBrewIds.includes(id))continue;const brew=brews.find(x=>x.id===id)!,state=brewStates.get(id)!;if(state.kind==="missing"){const write=await this.remote.createBrew(toMigrationBaseBrew(brew));const failure=this.mapRemote(write,cp,"brew",id);if(failure)return failure}cp={...cp,migratedBrewIds:done(cp.migratedBrewIds,id)}}const saved=this.checkpoints.update(cp);if(!saved.ok)return{ok:false,code:"checkpoint_write_failed",message:saved.message}}
  for(const batch of chunkMigrationIds(plans.map(x=>x.id))){for(const id of batch){if(cp.migratedSuggestedPlanIds.includes(id))continue;const plan=plans.find(x=>x.id===id)!,state=planStates.get(id)!;if(state.kind==="missing"){const write=await this.remote.createPlan(plan);const failure=this.mapRemote(write,cp,"suggested_plan",id);if(failure)return failure}cp={...cp,migratedSuggestedPlanIds:done(cp.migratedSuggestedPlanIds,id)}}const saved=this.checkpoints.update(cp);if(!saved.ok)return{ok:false,code:"checkpoint_write_failed",message:saved.message}}
  for(const brew of brews.filter(x=>x.sourceSuggestedPlanId)){if(cp.patchedBrewIds.includes(brew.id))continue;const latest=await this.remote.readBrew(brew.id);const failure=this.mapRemote(latest,cp,"brew_patch",brew.id);if(failure)return failure;if(!latest.ok||latest.value.state!=="active")return this.failure("graph_reference_missing","Base Cloud Brew is missing before patch.",cp,"brew_patch",brew.id);if(!sameMigrationEntity(brew,latest.value.entity)){const write=await this.remote.patchBrew(buildBrewReferencePatch(brew,latest.value.entity),latest.value.revision);const failed=this.mapRemote(write,cp,"brew_patch",brew.id);if(failed)return failed}cp={...cp,patchedBrewIds:done(cp.patchedBrewIds,brew.id)};const saved=this.checkpoints.update(cp);if(!saved.ok)return{ok:false,code:"checkpoint_write_failed",message:saved.message}}
  return this.verifyAndComplete(cp,profile,brews,plans)}
 async verifyAndComplete(cp:MigrationEngineCheckpoint,profile:StoredUserProfile,brews:Brew[],plans:SuggestedBrewPlan[]):Promise<MigrationEngineResult>{const rp=await this.remote.readProfile(),rb=await this.remote.listBrews(),rs=await this.remote.listPlans();const fp=this.mapRemote(rp,cp,"profile",null);if(fp)return fp;const fb=this.mapRemote(rb,cp,"verification",null);if(fb)return fb;const fs=this.mapRemote(rs,cp,"verification",null);if(fs)return fs;if(!rp.ok||!rb.ok||!rs.ok)return this.failure("remote_verification_failed","Cloud verification failed.",cp,"verification");if(rp.value.state!=="active"||classifyProfileMigrationState(profile,rp.value.entity)!=="matching")return this.failure("remote_verification_failed","Cloud Profile verification failed.",cp,"verification");const brewMap=new Map(rb.value.map(x=>[x.id,x])),planMap=new Map(rs.value.map(x=>[x.id,x]));if(brews.some(x=>!brewMap.has(x.id)||!sameMigrationEntity(x,brewMap.get(x.id)!))||plans.some(x=>!planMap.has(x.id)||!sameMigrationEntity(x,planMap.get(x.id)!)))return this.failure("remote_verification_failed","Cloud entity verification failed.",cp,"verification");const graph=validateLocalCloudMigrationGraph({profile,brews:brews.map(x=>brewMap.get(x.id)!),suggestedPlans:plans.map(x=>planMap.get(x.id)!)});if(!graph.valid)return this.failure("remote_verification_failed","Cloud graph verification failed.",cp,"verification");const completed=migrationEngineCheckpointSchema.parse({...cp,status:"completed",completedAt:this.now(),lastAttemptAt:this.now(),graphVerified:true,errorCode:null,failedEntityType:null,failedEntityId:null});const saved=this.checkpoints.markCompleted(completed);return saved.ok?{ok:true,checkpoint:completed}:{ok:false,code:"checkpoint_write_failed",message:saved.message}}
}
