import{describe,expect,it,vi}from"vitest";import type{Brew,MigrationEngineCheckpoint,StartCloudMigrationCommand,SuggestedBrewPlan}from"@/domain";import{buildBrewReferencePatch,chunkMigrationIds,classifyProfileMigrationState,createReviewFingerprint,migrationEngineErrorCodeSchema,sameMigrationEntity,toMigrationBaseBrew}from"@/domain";import{createFullDemoFixtures}from"@/dev/demo-fixtures";import type{LocalRepositoryBundle}from"@/infrastructure/repositories/repository-composition";import type{CloudMigrationGateway,GatewayResult}from"@/infrastructure/supabase/cloud-migration-remote-gateway";import type{RemoteMigrationRecord}from"@/infrastructure/supabase/remote-repository-contracts";import{CloudMigrationCheckpointRepository}from"@/repositories/cloud-migration-checkpoint-repository";import type{StoredUserProfile}from"@/repositories/user-profile-repository";import{MigrationReviewService}from"./migration-review-service";import{LocalToCloudMigrationService}from"./local-to-cloud-migration-service";
const now="2026-08-05T00:00:00.000Z",userId="authenticated-user",fixtures=createFullDemoFixtures();const plan=fixtures.plans.find(x=>x.id==="demo-plan-completed")!,source=fixtures.brews.find(x=>x.id===plan.sourceBrewId)!,result=fixtures.brews.find(x=>x.id===plan.resultingBrewId)!;const profile:StoredUserProfile={profile:{id:"local-user",displayName:"Demo Brewer",experienceLevel:"developing",currentNeeds:["improve_consistency","track_and_compare"],createdAt:now,updatedAt:now},selectedNeeds:["improve_consistency","track_and_compare"],onboardingCompleted:true};
function localBundle(brews:Brew[]=[source,result],plans:SuggestedBrewPlan[]=[plan],stored:StoredUserProfile|null=profile){const writes={profile:vi.fn(),brew:vi.fn(),plan:vi.fn()};const bundle:LocalRepositoryBundle={userProfileRepository:{load:()=>stored?{status:"found",value:stored}:{status:"empty"},save:writes.profile,remove:vi.fn()},brewRepository:{listAll:()=>({ok:true,value:brews}),createDraft:writes.brew,getById:vi.fn(),findBySourceSuggestedPlanId:vi.fn(),listDrafts:vi.fn(),listJournalEntries:vi.fn(),upsertMany:vi.fn(),removeByIdPrefix:vi.fn(),updateDraft:vi.fn(),deleteDraft:vi.fn()},suggestedPlanRepository:{list:()=>({ok:true,value:plans}),create:writes.plan,getById:vi.fn(),findByResultingBrewId:vi.fn(),listBySourceBrewId:vi.fn(),upsertMany:vi.fn(),removeByIdPrefix:vi.fn(),update:vi.fn(),markUsed:vi.fn()},recipeRepository:{listRecipes:async()=>[],getRecipeById:vi.fn()}};return{bundle,writes}}
class FakeGateway implements CloudMigrationGateway{profile:StoredUserProfile|null=null;brews=new Map<string,{entity:Brew;revision:number;deleted?:boolean}>();plans=new Map<string,{entity:SuggestedBrewPlan;revision:number;deleted?:boolean}>();failPlanOnce=false;invalidBrewId:string|null=null;patchRevisions:number[]=[];calls:string[]=[];
 async readProfile(){return{ok:true as const,value:this.profile?{state:"active" as const,entity:this.profile,revision:1}:{state:"missing" as const}}}async createProfile(p:StoredUserProfile){this.calls.push("create-profile");this.profile=p;return{ok:true as const,value:p}}async updateProfile(p:StoredUserProfile){this.calls.push("update-profile");this.profile=p;return{ok:true as const,value:p}}
 async readBrew(id:string):Promise<GatewayResult<RemoteMigrationRecord<Brew>>>{const r=this.brews.get(id);if(this.invalidBrewId===id)return{ok:true,value:{state:"invalid"}};return{ok:true,value:!r?{state:"missing"}:r.deleted?{state:"deleted",revision:r.revision}:{state:"active",entity:r.entity,revision:r.revision}}}async createBrew(b:Brew){this.calls.push(`create-brew:${b.id}`);this.brews.set(b.id,{entity:structuredClone(b),revision:1});return{ok:true as const,value:b}}async patchBrew(b:Brew,r:number){this.calls.push(`patch-brew:${b.id}`);this.patchRevisions.push(r);this.brews.set(b.id,{entity:structuredClone(b),revision:r+1});return{ok:true as const,value:b,revision:r+1}}
 async readPlan(id:string):Promise<GatewayResult<RemoteMigrationRecord<SuggestedBrewPlan>>>{const r=this.plans.get(id);return{ok:true,value:!r?{state:"missing"}:r.deleted?{state:"deleted",revision:r.revision}:{state:"active",entity:r.entity,revision:r.revision}}}async createPlan(p:SuggestedBrewPlan){this.calls.push(`create-plan:${p.id}`);if(this.failPlanOnce){this.failPlanOnce=false;return{ok:false as const,code:"persistence_failed" as const,message:"safe failure"}}this.plans.set(p.id,{entity:structuredClone(p),revision:1});return{ok:true as const,value:p}}async patchPlan(p:SuggestedBrewPlan,r:number){this.plans.set(p.id,{entity:p,revision:r+1});return{ok:true as const,value:p}}async listBrews(){return{ok:true as const,value:[...this.brews.values()].filter(x=>!x.deleted).map(x=>x.entity)}}async listPlans(){return{ok:true as const,value:[...this.plans.values()].filter(x=>!x.deleted).map(x=>x.entity)}}}
function storage(){let raw:string|null=null;return{getItem:()=>raw,setItem:(_k:string,v:string)=>{raw=v},raw:()=>raw}}async function setup(gateway=new FakeGateway(),brews=[source,result],plans=[plan]){const local=localBundle(brews,plans),store=storage(),checkpoints=new CloudMigrationCheckpointRepository(store),review=await new MigrationReviewService(local.bundle).review(),progress:MigrationEngineCheckpoint[]=[];const service=new LocalToCloudMigrationService(local.bundle,gateway,checkpoints,userId,()=>now,cp=>progress.push(cp));return{...local,gateway,store,checkpoints,review,service,progress,command:{consentConfirmed:true,reviewFingerprint:review.reviewFingerprint}as const}}
describe("migration consent and preparation",()=>{
 it("keeps the start command limited to consent and review fingerprint",()=>{const command:StartCloudMigrationCommand={consentConfirmed:true,reviewFingerprint:"review-v1-test"};expect(command).toEqual({consentConfirmed:true,reviewFingerprint:"review-v1-test"})});
 it("rejects missing consent without remote calls",async()=>{const s=await setup();const r=await s.service.prepare({consentConfirmed:false,reviewFingerprint:s.review.reviewFingerprint} as never);expect(r).toMatchObject({ok:false,code:"consent_required"});expect(s.gateway.calls).toEqual([])});
 it("accepts the deterministic current review fingerprint",async()=>{const s=await setup();expect((await s.service.prepare(s.command)).ok).toBe(true)});
 it("rejects an outdated review fingerprint",async()=>{const s=await setup();expect(await s.service.prepare({...s.command,reviewFingerprint:"review-v1-old"})).toMatchObject({ok:false,code:"review_outdated"})});
 it("rejects an invalid local graph before remote reads",async()=>{const s=await setup(new FakeGateway(),[result],[plan]);expect(await s.service.start(s.command)).toMatchObject({ok:false,code:"local_data_invalid"});expect(s.gateway.calls).toEqual([])});
 it("creates a fingerprint that changes with local content but not ordering",()=>{const a=createReviewFingerprint({profile,brews:[source,result],suggestedPlans:[plan],recipeCount:0}),b=createReviewFingerprint({profile,brews:[result,source],suggestedPlans:[plan],recipeCount:0}),c=createReviewFingerprint({profile,brews:[{...source,recordStatus:"archived"},result],suggestedPlans:[plan],recipeCount:0});expect(a).toBe(b);expect(a).not.toBe(c)});
});
describe("migration projections and profile policy",()=>{
 it("compares product content while ignoring database updatedAt",()=>expect(sameMigrationEntity({...source,updatedAt:"2026-01-01T00:00:00.000Z"},{...source,updatedAt:"2026-02-01T00:00:00.000Z"})).toBe(true));
 it("neutralizes a circular Brew reference without modifying Local",()=>{const before=structuredClone(result),base=toMigrationBaseBrew(result);expect(base).toMatchObject({id:result.id,sourceType:"recipe"});expect(base.sourceSuggestedPlanId).toBeUndefined();expect(result).toEqual(before)});
 it("restores the source Plan reference while preserving payloads",()=>{const base=toMigrationBaseBrew(result),patched=buildBrewReferencePatch(result,base);expect(patched.sourceSuggestedPlanId).toBe(plan.id);expect(patched.recipeSnapshot).toEqual(result.recipeSnapshot);expect(patched.stageResults).toEqual(result.stageResults)});
 it("never changes targets into actual measurements",()=>{const base=toMigrationBaseBrew(result);expect(base.actualTotalWater).toBe(result.actualTotalWater);expect(base.stageResults.every(x=>x.actualWeight===null)).toBe(true)});
 it.each([[null,"missing_remote"],[profile,"matching"]]as const)("classifies profile state %s",(remote,expected)=>expect(classifyProfileMigrationState(profile,remote)).toBe(expected));
 it("recognizes only the conservative Coffee Brewer bootstrap",()=>{const bootstrap={...profile,profile:{...profile.profile,displayName:"Coffee Brewer",experienceLevel:"beginner" as const,currentNeeds:[]},selectedNeeds:[],onboardingCompleted:false};expect(classifyProfileMigrationState(profile,bootstrap)).toBe("bootstrap");expect(classifyProfileMigrationState(profile,{...bootstrap,profile:{...bootstrap.profile,displayName:"email-name"}})).toBe("profile_conflict")});
 it("uses deterministic batches of 25",()=>{const ids=Array.from({length:51},(_,i)=>`id-${String(50-i).padStart(2,"0")}`),chunks=chunkMigrationIds(ids);expect(chunks.map(x=>x.length)).toEqual([25,25,1]);expect(chunks.flat()).toEqual([...ids].sort())});
});
describe("LocalToCloudMigrationService execution",()=>{
 it("migrates Profile, base Brews, Plan, patches, verifies, and completes",async()=>{const s=await setup(),r=await s.service.start(s.command);expect(r.ok&&r.checkpoint.status).toBe("completed");expect(s.gateway.calls[0]).toBe("create-profile");expect(s.gateway.calls.findIndex(x=>x.startsWith("create-plan"))).toBeGreaterThan(s.gateway.calls.findIndex(x=>x.startsWith("create-brew")));expect(s.gateway.calls.some(x=>x.startsWith("patch-brew"))).toBe(true);expect(r.ok&&r.checkpoint.graphVerified).toBe(true)});
 it("keeps every Brew and Plan ID unchanged",async()=>{const s=await setup();await s.service.start(s.command);expect([...s.gateway.brews.keys()].sort()).toEqual([source.id,result.id].sort());expect([...s.gateway.plans.keys()]).toEqual([plan.id])});
 it("uses the authenticated owner for Profile rather than the Local id",async()=>{const s=await setup();await s.service.start(s.command);expect(s.gateway.profile?.profile.id).toBe(userId)});
 it("skips matching entities without duplicate creates",async()=>{const s=await setup();s.gateway.profile={...profile,profile:{...profile.profile,id:userId}};s.gateway.brews.set(source.id,{entity:source,revision:2});s.gateway.brews.set(result.id,{entity:result,revision:3});s.gateway.plans.set(plan.id,{entity:plan,revision:4});const r=await s.service.start(s.command);expect(r.ok).toBe(true);expect(s.gateway.calls.filter(x=>x.startsWith("create-")).length).toBe(0)});
 it("rejects conflicting remote Brew before any write",async()=>{const s=await setup();s.gateway.brews.set(source.id,{entity:{...source,recordStatus:"archived"},revision:1});const r=await s.service.start(s.command);expect(r).toMatchObject({ok:false,code:"remote_entity_conflict"});expect(s.gateway.calls).toEqual([])});
 it("rejects soft-deleted Remote Brew without reviving it",async()=>{const s=await setup();s.gateway.brews.set(source.id,{entity:source,revision:1,deleted:true});expect(await s.service.start(s.command)).toMatchObject({ok:false,code:"remote_entity_deleted"});expect(s.gateway.calls).toEqual([])});
 it("rejects invalid Remote Brew",async()=>{const s=await setup();s.gateway.invalidBrewId=source.id;expect(await s.service.start(s.command)).toMatchObject({ok:false,code:"remote_row_invalid"})});
 it("rejects a non-bootstrap Profile conflict before entity writes",async()=>{const s=await setup();s.gateway.profile={...profile,profile:{...profile.profile,displayName:"Cloud Edited",id:userId}};expect(await s.service.start(s.command)).toMatchObject({ok:false,code:"profile_conflict"});expect(s.gateway.calls).toEqual([])});
 it("updates a conservative bootstrap Profile",async()=>{const s=await setup();s.gateway.profile={...profile,profile:{...profile.profile,id:userId,displayName:"Coffee Brewer",experienceLevel:"beginner",currentNeeds:[]},selectedNeeds:[],onboardingCompleted:false};expect((await s.service.start(s.command)).ok).toBe(true);expect(s.gateway.calls).toContain("update-profile")});
 it("persists batch progress and resumes after a Plan write failure",async()=>{const s=await setup();s.gateway.failPlanOnce=true;const first=await s.service.start(s.command);expect(first).toMatchObject({ok:false,code:"remote_write_failed"});expect(first.checkpoint?.migratedBrewIds).toHaveLength(2);const second=await s.service.retry();expect(second.ok&&second.checkpoint.status).toBe("completed");expect(s.gateway.calls.filter(x=>x.startsWith("create-brew")).length).toBe(2)});
 it("increments attempt count on retry",async()=>{const s=await setup();s.gateway.failPlanOnce=true;await s.service.start(s.command);const r=await s.service.retry();expect(r.ok&&r.checkpoint.attemptCount).toBe(2)});
 it("uses latest expected revision for Brew reference patch",async()=>{const s=await setup();await s.service.start(s.command);expect(s.gateway.patchRevisions).toEqual([1])});
 it("does not rerun a completed checkpoint",async()=>{const s=await setup();await s.service.start(s.command);expect(await s.service.start(s.command)).toMatchObject({ok:false,code:"migration_already_completed"})});
 it("fails verification when a Remote Brew is missing",async()=>{const s=await setup();const original=s.gateway.listBrews.bind(s.gateway);s.gateway.listBrews=async()=>{const r=await original();return r.ok?{...r,value:r.value.filter(x=>x.id!==source.id)}:r};expect(await s.service.start(s.command)).toMatchObject({ok:false,code:"remote_verification_failed"})});
 it("preserves Local repositories and never calls their writes",async()=>{const s=await setup(),before=structuredClone([source,result,plan]);await s.service.start(s.command);expect(s.writes.profile).not.toHaveBeenCalled();expect(s.writes.brew).not.toHaveBeenCalled();expect(s.writes.plan).not.toHaveBeenCalled();expect([source,result,plan]).toEqual(before)});
 it("emits real checkpoint counts",async()=>{const s=await setup();await s.service.start(s.command);expect(s.progress[0]).toMatchObject({totalBrewCount:2,totalSuggestedPlanCount:1,totalBrewPatchCount:1})});
});
describe("safe migration errors",()=>{it.each(migrationEngineErrorCodeSchema.options)("accepts normalized error %s",code=>expect(migrationEngineErrorCodeSchema.parse(code)).toBe(code))});
