import type { BrewAnalysisInput, BrewAnalysisResult } from "@/domain";
import { analysisDataQualitySchema, brewAnalysisResultSchema } from "@/domain";
import type { BrewAnalysisProvider } from "./brew-analysis-provider";
const evidence = (field: string, label: string, value: string) => [{ field, label, value }];
export class RuleBasedBrewAnalysisProvider implements BrewAnalysisProvider {
  readonly provider = "local_mock"; readonly model = "rule-based-v1";
  async analyze(input: BrewAnalysisInput): Promise<BrewAnalysisResult> {
    const strengths: BrewAnalysisResult["strengths"] = [], observations: BrewAnalysisResult["observations"] = [], possibleIssues: BrewAnalysisResult["possibleIssues"] = [], recommendations: BrewAnalysisResult["recommendations"] = [];
    const actual = input.execution.actualTotalTime, target = input.planned.expectedTotalTime, feedback = input.feedback as null | { bitterness?: number; acidity?: number; sweetness?: number };
    if (actual != null) { const delta = actual - target; if (Math.abs(delta) <= 15) strengths.push({ id: "timing-close", title: "Timing stayed close to plan", description: "The total brew time was near the planned duration.", confidence: "high", evidence: evidence("execution.actualTotalTime", "Actual / target time", `${actual}s / ${target}s`) }); else { const long = delta > 0; observations.push({ id: "time-delta", title: long ? "Brew ran longer than planned" : "Brew finished faster than planned", description: `Total time differed from the plan by ${Math.abs(delta)} seconds.`, confidence: "high", evidence: evidence("execution.actualTotalTime", "Time difference", `${delta > 0 ? "+" : ""}${delta}s`) }); possibleIssues.push({ id: "drawdown-possibility", title: long ? "Heavier extraction may be possible" : "Faster drawdown may be possible", description: "Timing alone cannot establish extraction outcome; taste feedback is needed for a stronger interpretation.", confidence: feedback ? "medium" : "low", evidence: evidence("execution.actualTotalTime", "Actual / target time", `${actual}s / ${target}s`) }); } }
    if (feedback?.bitterness && feedback.bitterness >= 4) recommendations.push({ id: "bitterness-control", title: "Test one controlled adjustment", description: "High reported bitterness supports a cautious next-cup experiment.", priority: "high", rationale: "Change only one variable so the next result remains comparable.", suggestedAdjustment: "Try a slightly coarser grind and keep other variables unchanged.", action: { type: "adjust_grind", direction: "coarser", magnitude: "slight" }, confidence: "medium", evidence: evidence("feedback.bitterness", "Bitterness rating", `${feedback.bitterness}/5`) });
    if (feedback?.acidity && feedback.acidity >= 4 && (!feedback.sweetness || feedback.sweetness <= 2)) possibleIssues.push({ id: "sharp-cup", title: "The cup may have felt sharp", description: "High acidity together with low sweetness can describe a sharper sensory balance, but remains subjective.", confidence: "medium", evidence: [...evidence("feedback.acidity", "Acidity", `${feedback.acidity}/5`), ...evidence("feedback.sweetness", "Sweetness", `${feedback.sweetness ?? "missing"}/5`)] });
    if (!feedback) recommendations.push({ id: "add-feedback", title: "Add flavor feedback next time", description: "Taste feedback would make future observations more specific.", priority: "medium", rationale: "Execution timing cannot establish flavor outcome by itself.", suggestedAdjustment: "Record overall impression and one or two sensory ratings.", action: { type: "collect_more_data", fields: ["flavorFeedback"] }, confidence: "high", evidence: evidence("missingData", "Missing input", "Flavor feedback") });
    const missing = input.missingData, hasFeedback = !missing.includes("flavorFeedback"), hasRecord = !missing.includes("recordDetails"), hasActual = !missing.includes("actualDose") || !missing.includes("actualWater") || !missing.includes("actualTemperature");
    const dataQuality = analysisDataQualitySchema.parse({ level: hasFeedback && hasRecord && hasActual ? "good" : hasFeedback || hasRecord || hasActual ? "partial" : "limited", missingFields: missing, notes: [!hasFeedback ? "Taste outcomes cannot be evaluated without user feedback." : "User feedback is available for subjective context.", !hasActual ? "No weight or temperature differences were inferred because actual measurements are missing." : "Some actual measurements support deterministic comparisons."] });
    return brewAnalysisResultSchema.parse({ summary: feedback ? "This local preview found a small set of signals grounded in your Brew record and feedback." : "This local preview can compare timing, but taste conclusions remain limited without feedback.", strengths, observations, possibleIssues, recommendations: recommendations.slice(0, 3), dataQuality, disclaimer: "Local preview only. These suggestions are not scientific extraction measurements; change one variable at a time and use your own taste as the final guide." });
  }
}
