import { describe, expect, it } from "vitest";
import { isAnalysisOutdated } from "@/domain";
import { getSourceBrewSuggestedPlanProjection } from "@/application/suggested-plan-projection";
import { DemoSeedService } from "./demo-seed-service";
import { createFullDemoFixtures, createMigrationSmokeFixtures, DEMO_PREFIX, MIGRATION_SMOKE_PREFIX } from "./demo-fixtures";
import { validateLocalCloudMigrationGraph } from "@/domain";
import { demoFixtureSchema } from "./demo-seed-schema";
import { LocalBrewRepository } from "@/repositories/local-brew-repository";
import { LocalSuggestedPlanRepository } from "@/repositories/local-suggested-plan-repository";
import { LocalUserProfileRepository } from "@/repositories/local-user-profile-repository";

class MemoryStorage { values = new Map<string,string>(); getItem(key:string){return this.values.get(key)??null} setItem(key:string,value:string){this.values.set(key,value)} removeItem(key:string){this.values.delete(key)} }
function setup(environment: "test" | "development" | "production" = "test"){const storage=new MemoryStorage(),profiles=new LocalUserProfileRepository(storage),brews=new LocalBrewRepository(storage),plans=new LocalSuggestedPlanRepository(storage),service=new DemoSeedService(profiles,brews,plans,environment);return{storage,profiles,brews,plans,service}}

describe("Development demo fixtures",()=>{
  it("validates the full fixture graph at runtime",()=>expect(demoFixtureSchema.safeParse(createFullDemoFixtures()).success).toBe(true));
  it("uses unique prefixed Brew and Plan IDs",()=>{const fixture=createFullDemoFixtures(),brewIds=fixture.brews.map((item)=>item.id),planIds=fixture.plans.map((item)=>item.id);expect(new Set(brewIds).size).toBe(brewIds.length);expect(new Set(planIds).size).toBe(planIds.length);expect([...brewIds,...planIds].every((id)=>id.startsWith(DEMO_PREFIX))).toBe(true)});
  it("aligns Plan mappings and usedAt to resulting execution",()=>{const fixture=createFullDemoFixtures(),map=new Map(fixture.brews.map((brew)=>[brew.id,brew]));for(const plan of fixture.plans){if(!plan.resultingBrewId)continue;const brew=map.get(plan.resultingBrewId);if(!brew)continue;expect(brew.sourceSuggestedPlanId).toBe(plan.id);if(plan.status==="used")expect(plan.usedAt).toBe(brew.startedAt)}});
  it("contains pending, accepted, and overridden handoffs",()=>{const decisions=createFullDemoFixtures().brews.flatMap((brew)=>brew.suggestedPlanHandoff?[brew.suggestedPlanHandoff.userDecision]:[]);expect(decisions).toEqual(expect.arrayContaining(["pending","accepted","overridden"]))});
  it("keeps recipe drafts free of Suggested Plan handoff",()=>{expect(createFullDemoFixtures().brews.filter((brew)=>brew.sourceType==="recipe").every((brew)=>!brew.suggestedPlanHandoff&&!brew.sourceSuggestedPlanId)).toBe(true)});
  it("provides current, outdated, and failed analysis states",()=>{const brews=createFullDemoFixtures().brews,outdated=brews.find((brew)=>brew.id.includes("completed-draft")),failed=brews.find((brew)=>brew.id.includes("failed-analysis"));expect(outdated&&isAnalysisOutdated(outdated)).toBe(true);expect(failed).toMatchObject({analysisStatus:"failed",analysis:{status:"completed"},analysisAttempt:{status:"failed"}})});
  it("contains completed draft and in-progress Brew states",()=>{const brews=createFullDemoFixtures().brews;expect(brews.some((brew)=>brew.executionStatus==="completed"&&brew.recordStatus==="draft")).toBe(true);expect(brews.some((brew)=>brew.executionStatus==="in_progress"&&brew.stageResults.length>0)).toBe(true)});
  it("sorts multiple Plans for a Source Brew deterministically",()=>{const fixture=createFullDemoFixtures(),source=fixture.brews.find((brew)=>brew.id==="demo-brew-b-complete")!,map=new Map(fixture.brews.map((brew)=>[brew.id,brew])),projection=getSourceBrewSuggestedPlanProjection(source,fixture.plans,map);expect(projection.totalPlans).toBeGreaterThan(1);expect(projection.plans.map((plan)=>plan.updatedAt)).toEqual([...projection.plans.map((plan)=>plan.updatedAt)].sort().reverse())});
  it("seeds idempotently without duplicating fixtures",()=>{const{service,brews,plans}=setup();expect(service.seed("full").ok).toBe(true);expect(service.seed("full").ok).toBe(true);expect(brews.listAll().value).toHaveLength(createFullDemoFixtures().brews.length);expect(plans.list().value).toHaveLength(createFullDemoFixtures().plans.length)});
  it("preserves non-demo records during seed merge",()=>{const{service,brews}=setup(),user={...createFullDemoFixtures().brews[0],id:"user:brew:keep"};expect(brews.createDraft(user).ok).toBe(true);expect(service.seed("full").ok).toBe(true);expect(brews.getById(user.id).value?.id).toBe(user.id)});
  it("requires confirmation before replacing a non-demo profile",()=>{const{service,profiles}=setup();profiles.save({displayName:"Real User",experienceLevel:"beginner",selectedNeeds:[]});expect(service.seed("full")).toMatchObject({ok:false,code:"confirmation_required"});expect(service.seed("full",{overwriteProfile:true}).ok).toBe(true)});
  it("reset removes only CupMaster repository data and leaves unrelated storage",()=>{const{service,storage,brews,plans,profiles}=setup();storage.setItem("another-app:key","keep");service.seed("full");expect(service.resetAll().ok).toBe(true);expect(brews.listAll().value).toEqual([]);expect(plans.list().value).toEqual([]);expect(profiles.load().status).toBe("empty");expect(storage.getItem("another-app:key")).toBe("keep")});
  it("blocks seed and reset writes in production",()=>{const{service,brews}=setup("production");expect(service.seed("full")).toMatchObject({ok:false,code:"production_blocked"});expect(service.resetAll().ok).toBe(false);expect(brews.listAll().value).toEqual([])});
  it("validates the fixed migration smoke graph",()=>{const fixture=createMigrationSmokeFixtures();expect(demoFixtureSchema.safeParse(fixture).success).toBe(true);expect(validateLocalCloudMigrationGraph({profile:{profile:{id:"local",displayName:fixture.profile.displayName,experienceLevel:"developing",currentNeeds:["track_and_compare"],createdAt:"2026-08-01T00:00:00.000Z",updatedAt:"2026-08-01T00:00:00.000Z"},selectedNeeds:["track_and_compare"],onboardingCompleted:true},brews:fixture.brews,suggestedPlans:fixture.plans}).valid).toBe(true)});
  it("uses unique migration-smoke IDs and complete bidirectional references",()=>{const fixture=createMigrationSmokeFixtures(),ids=[...fixture.brews.map(x=>x.id),...fixture.plans.map(x=>x.id)];expect(ids.every(id=>id.startsWith(MIGRATION_SMOKE_PREFIX))).toBe(true);expect(new Set(ids).size).toBe(ids.length);expect(fixture.brews.find(x=>x.sourceSuggestedPlanId)?.sourceSuggestedPlanId).toBe(fixture.plans[0].id);expect(fixture.plans[0].resultingBrewId).toBe(fixture.brews.find(x=>x.sourceSuggestedPlanId)?.id)});
  it("seeds the smoke graph idempotently into Local repositories only",()=>{const{service,brews,plans}=setup();expect(service.seed("migration_smoke",{overwriteProfile:true}).ok).toBe(true);expect(service.seed("migration_smoke",{overwriteProfile:true}).ok).toBe(true);expect(brews.listAll().value).toHaveLength(2);expect(plans.list().value).toHaveLength(1)});
  it("resets only migration smoke Local records",()=>{const{service,brews}=setup();const keep={...createFullDemoFixtures().brews[0],id:"user-brew-keep"};brews.createDraft(keep);service.seed("migration_smoke",{overwriteProfile:true});expect(service.resetMigrationSmoke()).toMatchObject({ok:true,removedBrews:2,removedPlans:1});expect(brews.getById(keep.id).value).toBeTruthy()});
});
